// Core sprites owned by the engine: the crowd runner (BACK view — camera chases
// the crowd) and shop preview body. Skins recolor these via palette override —
// keys: h hair, s skin, t shirt, T shirt-dark, l pants, L pants-dark, b boots.
export const CORE = {
  runner_back: {
    w: 12, h: 18, anchor: 'bottom',
    palette: {
      h: '#4a2f1b', s: '#d8a077', t: '#00afaf', T: '#008f8f',
      l: '#3d55b8', L: '#2e4090', b: '#6e6e6e',
    },
    frames: [
      [
        "...hhhhhh...",
        "...hhhhhh...",
        "...hhhhhh...",
        "...hhhhhh...",
        "...hhhhhh...",
        "....ssss....",
        "..tttttttt..",
        "..tTttttTt..",
        "..tttttttt..",
        "..tTttttTt..",
        "..tttttttt..",
        "..sTttttTs..",
        "...tttttt...",
        "...llLLll...",
        "...llLLll...",
        "...ll..ll...",
        "...bb..bb...",
        "...bb..bb...",
      ],
      [
        "...hhhhhh...",
        "...hhhhhh...",
        "...hhhhhh...",
        "...hhhhhh...",
        "...hhhhhh...",
        "....ssss....",
        "..tttttttt..",
        "..sTttttTt..",
        "..tttttttt..",
        "..tTttttTs..",
        "..tttttttt..",
        "..tTttttTt..",
        "...tttttt...",
        "...llLLll...",
        "...llLLll...",
        "...bb..ll...",
        "...bb..ll...",
        "...bb..bb...",
      ],
    ],
  },
  // Front body for the shop preview (head drawn separately from head_* sprites).
  runner_body_front: {
    w: 12, h: 12, anchor: 'bottom',
    palette: {
      s: '#d8a077', t: '#00afaf', T: '#008f8f',
      l: '#3d55b8', L: '#2e4090', b: '#6e6e6e',
    },
    frames: [
      [
        "..tttttttt..",
        "..tTttttTt..",
        "..tttttttt..",
        "..tTttttTt..",
        "..sTttttTs..",
        "...tttttt...",
        "...llLLll...",
        "...llLLll...",
        "...ll..ll...",
        "...ll..ll...",
        "...bb..bb...",
        "...bb..bb...",
      ],
    ],
  },
  // Enderman lives in core (End-biome enemy) so the roster works even if a pack fails.
  enderman: {
    w: 14, h: 28, anchor: 'bottom',
    palette: { k: '#1c1c1c', K: '#0e0e0e', p: '#c76bff', P: '#8b3fd6' },
    frames: [
      [
        "...kkkkkkkk...",
        "...kKkkkkKk...",
        "...kkkkkkkk...",
        "...kkkkkkkk...",
        "...pPkkkkPp...",
        "...kkkkkkkk...",
        "...kKkkkkKk...",
        "...kkkkkkkk...",
        "..K..kkkk..K..",
        "..k..kKkk..k..",
        "..k..kkkk..k..",
        "..K..kkKk..K..",
        "..k..kkkk..k..",
        "..k..kKkk..k..",
        "..K..kkkk..K..",
        "..k..kkkk..k..",
        "..k..KkkK..k..",
        ".....kkkk.....",
        "....kk..kk....",
        "....kK..Kk....",
        "....kk..kk....",
        "....kk..kk....",
        "....Kk..kK....",
        "....kk..kk....",
        "....kk..kk....",
        "....kK..Kk....",
        "....kk..kk....",
        "....KK..KK....",
      ],
      [
        "...kkkkkkkk...",
        "...kKkkkkKk...",
        "...kkkkkkkk...",
        "...kkkkkkkk...",
        "...pPkkkkPp...",
        "...kkkkkkkk...",
        "...kKkkkkKk...",
        "...kkkkkkkk...",
        ".K...kkkk...K.",
        ".k...kKkk...k.",
        ".k...kkkk...k.",
        ".K...kkKk...K.",
        ".k...kkkk...k.",
        ".k...kKkk...k.",
        ".K...kkkk...K.",
        ".....kkkk.....",
        ".....KkkK.....",
        ".....kkkk.....",
        "....kk..kk....",
        "....kK..Kk....",
        "....kk..kk....",
        "....kk..kk....",
        "....Kk..kK....",
        "....kk..kk....",
        "....kk..kk....",
        "....kK..Kk....",
        "....kk..kk....",
        "....KK..KK....",
      ],
    ],
  },
  // Cosmetics: cape (palette-swapped per cape def), hat overlays, parrot pet.
  cape: {
    w: 8, h: 9, anchor: 'bottom',
    palette: { c: '#c8322a', C: '#8f1f14' },
    frames: [
      [
        "cccccccc",
        "cCccccCc",
        "cccccccc",
        "cCccccCc",
        "cccccccc",
        "cCccccCc",
        "cccccccc",
        "CcCccCcC",
        ".C.CC.C.",
      ],
      [
        "cccccccc",
        "cCccccCc",
        "cccccccc",
        ".ccccccc",
        ".cCccccC",
        "..cccccc",
        "..cCcccc",
        "..CcCccC",
        "...C.CC.",
      ],
    ],
  },
  hat_crown: {
    w: 10, h: 5, anchor: 'bottom',
    palette: { g: '#f3c53f', G: '#c29222', r: '#e04a3f' },
    frames: [
      [
        ".g..g..g..",
        ".g..g..g..",
        ".gggggggg.",
        ".gGrGGrGg.",
        ".gggggggg.",
      ],
    ],
  },
  hat_pumpkin: {
    w: 10, h: 7, anchor: 'bottom',
    palette: { o: '#e8871e', O: '#b5620f', s: '#4f7a1e' },
    frames: [
      [
        "....ss....",
        ".oooooooo.",
        "oOooooooOo",
        "oooOooOooo",
        "oOooooooOo",
        "oooooooooo",
        ".oooooooo.",
      ],
    ],
  },
  hat_slime: {
    w: 10, h: 6, anchor: 'bottom',
    palette: { g: '#7ee06a', G: '#4fb83f' },
    frames: [
      [
        "..gggggg..",
        ".gggggggg.",
        "gggGggGggg",
        "gggggggggg",
        ".gGggggGg.",
        "..g.gg.g..",
      ],
    ],
  },
  hat_tnt: {
    w: 10, h: 5, anchor: 'bottom',
    palette: { r: '#c8322a', R: '#8f1f14', w: '#e8e0d8', k: '#1a1a1a' },
    frames: [
      [
        ".rrrrrrrr.",
        "rrRrrrrRrr",
        "wwwwwwwwww",
        "wkwwkkwwkw",
        "rrRrrrrRrr",
      ],
    ],
  },
  hat_santa: {
    w: 10, h: 7, anchor: 'bottom',
    palette: { r: '#c8322a', R: '#8f1f14', w: '#ffffff' },
    frames: [
      [
        "..rrr.....",
        ".rrrrr....",
        ".rRrrrr...",
        "..rrrrrr..",
        "...rrrrrww",
        "wwwwwwwwww",
        "wwwwwwwwww",
      ],
    ],
  },
  parrot: {
    w: 10, h: 10, anchor: 'bottom',
    palette: { r: '#e0362b', b: '#3fa9ff', o: '#e8871e', k: '#0c0c0c', g: '#2eff70' },
    frames: [
      [
        "....rr....",
        "...rrrr...",
        "...rrkro..",
        "..rrrrrr..",
        ".bbrrrrr..",
        "bbbbrrrr..",
        "..bbrrr...",
        "...rrrr...",
        "..gg.rr...",
        ".gg.......",
      ],
      [
        "....rr....",
        "...rrrr...",
        "...rrkro..",
        "..rrrrrr..",
        "..rrrrrr..",
        "..bbrrrr..",
        ".bbbbrr...",
        "...rrrr...",
        "..gg.rr...",
        ".gg.......",
      ],
    ],
  },
  head_fallback: {
    w: 8, h: 8, anchor: 'center',
    palette: { h: '#4a2f1b', s: '#d8a077', e: '#ffffff', p: '#3d55b8', m: '#8a5a3a' },
    frames: [
      [
        "hhhhhhhh",
        "hhhhhhhh",
        "sshsshss",
        "ssssssss",
        "sepsspes",
        "ssssssss",
        "ssmmmmss",
        "ssssssss",
      ],
    ],
  },
};
