// Core sprites owned by the engine: the crowd runner (BACK view — camera chases
// the crowd) and shop preview body. Skins recolor these via palette override —
// keys: h hair, s skin, t shirt, T shirt-dark, l pants, L pants-dark, b boots.
export const CORE = {
  runner_back: {
    w: 12, h: 18, anchor: 'bottom',
    palette: {
      h: '#4a2f1b', s: '#d8a077', t: '#00afaf', T: '#008f8f',
      l: '#3d55b8', L: '#2e4090', b: '#6e6e6e',
    },
    frames: [
      [
        "...hhhhhh...",
        "...hhhhhh...",
        "...hhhhhh...",
        "...hhhhhh...",
        "...hhhhhh...",
        "....ssss....",
        "..tttttttt..",
        "..tTttttTt..",
        "..tttttttt..",
        "..tTttttTt..",
        "..tttttttt..",
        "..sTttttTs..",
        "...tttttt...",
        "...llLLll...",
        "...llLLll...",
        "...ll..ll...",
        "...bb..bb...",
        "...bb..bb...",
      ],
      [
        "...hhhhhh...",
        "...hhhhhh...",
        "...hhhhhh...",
        "...hhhhhh...",
        "...hhhhhh...",
        "....ssss....",
        "..tttttttt..",
        "..sTttttTt..",
        "..tttttttt..",
        "..tTttttTs..",
        "..tttttttt..",
        "..tTttttTt..",
        "...tttttt...",
        "...llLLll...",
        "...llLLll...",
        "...bb..ll...",
        "...bb..ll...",
        "...bb..bb...",
      ],
    ],
  },
  // Front body for the shop preview (head drawn separately from head_* sprites).
  runner_body_front: {
    w: 12, h: 12, anchor: 'bottom',
    palette: {
      s: '#d8a077', t: '#00afaf', T: '#008f8f',
      l: '#3d55b8', L: '#2e4090', b: '#6e6e6e',
    },
    frames: [
      [
        "..tttttttt..",
        "..tTttttTt..",
        "..tttttttt..",
        "..tTttttTt..",
        "..sTttttTs..",
        "...tttttt...",
        "...llLLll...",
        "...llLLll...",
        "...ll..ll...",
        "...ll..ll...",
        "...bb..bb...",
        "...bb..bb...",
      ],
    ],
  },
  // Villager head: bald brown head, unibrow, dot eyes, long central nose. Shared
  // by every home villager; profession is read from the robe body, not the face.
  head_villager: {
    w: 8, h: 8, anchor: 'center',
    palette: { s: '#a8763f', n: '#8a5f30', w: '#4a3420', k: '#241a10', m: '#7a5228' },
    frames: [
      [
        "ssssssss",
        "ssssssss",
        "swwwwwws",
        "sksnnsks",
        "sssnnsss",
        "sssnnsss",
        "ssmmmmss",
        "ssssssss",
      ],
    ],
  },
  // Villager robe body: crossed arms over a center apron stripe, robe to the feet.
  // Robe colours (r/R/a) are overridden per profession; s = hands.
  villager_body: {
    w: 12, h: 12, anchor: 'bottom',
    palette: { r: '#7a5a3a', R: '#5f4528', a: '#9a7a4a', s: '#a8763f' },
    frames: [
      [
        "..rrrrrrrr..",
        "..rrraarrr..",
        "..rRraarRr..",
        "..rrraarrr..",
        "..rssaassr..",
        "..rssaassr..",
        "..rrraarrr..",
        "..rrraarrr..",
        "..rRraarRr..",
        "..rrraarrr..",
        "..rrrrrrrr..",
        "...RR..RR...",
      ],
    ],
  },
  // Playmate ragdoll parts — recolored per skin (t/T shirt, s skin, l/L pants, b boots),
  // drawn as separate rotatable limbs so arms/legs dangle. Drawn top-down from a joint.
  pm_torso: {
    w: 8, h: 8, anchor: 'bottom',
    palette: { t: '#00afaf', T: '#008f8f', s: '#d8a077' },
    frames: [[
      "..ssss..",
      ".tTTTTt.",
      ".tttttt.",
      ".tTttTt.",
      ".tttttt.",
      ".tTttTt.",
      ".tttttt.",
      ".tttttt.",
    ]],
  },
  pm_arm: {
    w: 3, h: 8, anchor: 'center',
    palette: { t: '#00afaf', T: '#008f8f', s: '#d8a077' },
    frames: [[
      "tTt",
      "ttt",
      "tTt",
      "ttt",
      "tTt",
      "sss",
      "sss",
      "sss",
    ]],
  },
  pm_leg: {
    w: 3, h: 8, anchor: 'center',
    palette: { l: '#3d55b8', L: '#2e4090', b: '#6e6e6e' },
    frames: [[
      "lLl",
      "lll",
      "lLl",
      "lll",
      "lLl",
      "lll",
      "bbb",
      "bbb",
    ]],
  },
  // --- more cosmetic hats (authored in parallel, validated) ---
  hat_wizard: {
    w: 13, h: 11, anchor: 'bottom',
    palette: { p: '#5b3aa6', P: '#3a2472', s: '#f7d84b', y: '#ffe873', O: '#241546' },
    frames: [[
      "......pP.....",
      "......pP.....",
      ".....ppPP....",
      ".....psPP....",
      "....pppPPP...",
      "....pyPPsP...",
      "...pppyPPPP..",
      "...ppppsPPP..",
      "..pppyppPyPP.",
      ".OpppppPPPPPO",
      ".OOOOOOOOOOO.",
    ]],
  },
  hat_top: {
    w: 12, h: 10, anchor: 'bottom',
    palette: { k: '#1a1a1a', d: '#0a0a0a', h: '#3a3a3a', r: '#d8382e', R: '#a02820' },
    frames: [[
      "...dkkkkd...",
      "...dhkkkd...",
      "...dhkkkd...",
      "...dhkkkd...",
      "...dhkkkd...",
      "...dhkkkd...",
      "...drrrrd...",
      "...dRRRRd...",
      "dkkkkkkkkkkd",
      "dddddddddddd",
    ]],
  },
  hat_party: {
    w: 11, h: 11, anchor: 'bottom',
    palette: { p: '#ff5fa2', c: '#3fd6e0', y: '#ffe14d', o: '#7a2f5a', w: '#fff7fb' },
    frames: [[
      "....www....",
      "...wwwww...",
      ".....y.....",
      "....cpc....",
      "....ycy....",
      "...cpypc...",
      "...ycpcy...",
      "..cpycypc..",
      "..ycpypcy..",
      ".cpycpcypc.",
      "ooooooooooo",
    ]],
  },
  hat_flower: {
    w: 13, h: 6, anchor: 'bottom',
    palette: { p: '#ef6aa4', y: '#f5d13f', r: '#e0463b', g: '#5cb24c', G: '#357a2c' },
    frames: [[
      "..p.g.y.g.r..",
      "gpypgyrygryrg",
      ".gpg.gyg.grg.",
      "ggggggggggggg",
      "gGgGgGgGgGgGg",
      "GGGGGGGGGGGGG",
    ]],
  },
  hat_propeller: {
    w: 11, h: 9, anchor: 'bottom',
    palette: { r: '#e8493c', b: '#3b7dd8', D: '#7a2b23', s: '#c9ccd4', w: '#ffffff' },
    frames: [[
      "ww.......ww",
      ".sss.s.sss.",
      ".....s.....",
      "...bbrbb...",
      "..brrrrrb..",
      ".brrrrrrrb.",
      "bbrrrrrrrbb",
      "DbbbrbbbbD.",
      "DDDDDDDDDDD",
    ]],
  },
  hat_cowboy: {
    w: 14, h: 7, anchor: 'bottom',
    palette: { d: '#4a2f14', b: '#8a5a2b', l: '#a9764a', t: '#d9b380' },
    frames: [[
      "....dddddd....",
      "....dbllbd....",
      "....dbbbbd....",
      "...dttttttd...",
      "..lbbbbbbbbl..",
      "dbbbbbbbbbbbbd",
      ".dddddddddddd.",
    ]],
  },
  hat_cat: {
    w: 13, h: 6, anchor: 'bottom',
    palette: { d: '#241f28', f: '#4b4453', p: '#f4a9c6', P: '#dd80a5' },
    frames: [[
      "..d.......d..",
      ".dpd.....dpd.",
      "dpPpd...dpPpd",
      "dfffd...dfffd",
      "dfffffffffffd",
      "ddddddddddddd",
    ]],
  },
  hat_chef: {
    w: 12, h: 10, anchor: 'bottom',
    palette: { w: '#ffffff', e: '#e9edf4', s: '#c2c8d5', o: '#8f95a4' },
    frames: [[
      "....wwee....",
      "..wwwweeee..",
      ".wwwwweeeee.",
      "wwwwwweeeess",
      "wwwwweeeesss",
      ".wwwweeeess.",
      "..ssssssss..",
      "..wwwwwess..",
      "..wwwweess..",
      "..oooooooo..",
    ]],
  },
  // Enderman lives in core (End-biome enemy) so the roster works even if a pack fails.
  enderman: {
    w: 14, h: 28, anchor: 'bottom',
    palette: { k: '#1c1c1c', K: '#0e0e0e', p: '#c76bff', P: '#8b3fd6' },
    frames: [
      [
        "...kkkkkkkk...",
        "...kKkkkkKk...",
        "...kkkkkkkk...",
        "...kkkkkkkk...",
        "...pPkkkkPp...",
        "...kkkkkkkk...",
        "...kKkkkkKk...",
        "...kkkkkkkk...",
        "..K..kkkk..K..",
        "..k..kKkk..k..",
        "..k..kkkk..k..",
        "..K..kkKk..K..",
        "..k..kkkk..k..",
        "..k..kKkk..k..",
        "..K..kkkk..K..",
        "..k..kkkk..k..",
        "..k..KkkK..k..",
        ".....kkkk.....",
        "....kk..kk....",
        "....kK..Kk....",
        "....kk..kk....",
        "....kk..kk....",
        "....Kk..kK....",
        "....kk..kk....",
        "....kk..kk....",
        "....kK..Kk....",
        "....kk..kk....",
        "....KK..KK....",
      ],
      [
        "...kkkkkkkk...",
        "...kKkkkkKk...",
        "...kkkkkkkk...",
        "...kkkkkkkk...",
        "...pPkkkkPp...",
        "...kkkkkkkk...",
        "...kKkkkkKk...",
        "...kkkkkkkk...",
        ".K...kkkk...K.",
        ".k...kKkk...k.",
        ".k...kkkk...k.",
        ".K...kkKk...K.",
        ".k...kkkk...k.",
        ".k...kKkk...k.",
        ".K...kkkk...K.",
        ".....kkkk.....",
        ".....KkkK.....",
        ".....kkkk.....",
        "....kk..kk....",
        "....kK..Kk....",
        "....kk..kk....",
        "....kk..kk....",
        "....Kk..kK....",
        "....kk..kk....",
        "....kk..kk....",
        "....kK..Kk....",
        "....kk..kk....",
        "....KK..KK....",
      ],
    ],
  },
  // Cosmetics: cape (palette-swapped per cape def), hat overlays, parrot pet.
  cape: {
    w: 8, h: 9, anchor: 'bottom',
    palette: { c: '#c8322a', C: '#8f1f14' },
    frames: [
      [
        "cccccccc",
        "cCccccCc",
        "cccccccc",
        "cCccccCc",
        "cccccccc",
        "cCccccCc",
        "cccccccc",
        "CcCccCcC",
        ".C.CC.C.",
      ],
      [
        "cccccccc",
        "cCccccCc",
        "cccccccc",
        ".ccccccc",
        ".cCccccC",
        "..cccccc",
        "..cCcccc",
        "..CcCccC",
        "...C.CC.",
      ],
    ],
  },
  hat_crown: {
    w: 10, h: 5, anchor: 'bottom',
    palette: { g: '#f3c53f', G: '#c29222', r: '#e04a3f' },
    frames: [
      [
        ".g..g..g..",
        ".g..g..g..",
        ".gggggggg.",
        ".gGrGGrGg.",
        ".gggggggg.",
      ],
    ],
  },
  hat_pumpkin: {
    w: 10, h: 7, anchor: 'bottom',
    palette: { o: '#e8871e', O: '#b5620f', s: '#4f7a1e' },
    frames: [
      [
        "....ss....",
        ".oooooooo.",
        "oOooooooOo",
        "oooOooOooo",
        "oOooooooOo",
        "oooooooooo",
        ".oooooooo.",
      ],
    ],
  },
  hat_slime: {
    w: 10, h: 6, anchor: 'bottom',
    palette: { g: '#7ee06a', G: '#4fb83f' },
    frames: [
      [
        "..gggggg..",
        ".gggggggg.",
        "gggGggGggg",
        "gggggggggg",
        ".gGggggGg.",
        "..g.gg.g..",
      ],
    ],
  },
  hat_tnt: {
    w: 10, h: 5, anchor: 'bottom',
    palette: { r: '#c8322a', R: '#8f1f14', w: '#e8e0d8', k: '#1a1a1a' },
    frames: [
      [
        ".rrrrrrrr.",
        "rrRrrrrRrr",
        "wwwwwwwwww",
        "wkwwkkwwkw",
        "rrRrrrrRrr",
      ],
    ],
  },
  hat_santa: {
    w: 10, h: 7, anchor: 'bottom',
    palette: { r: '#c8322a', R: '#8f1f14', w: '#ffffff' },
    frames: [
      [
        "..rrr.....",
        ".rrrrr....",
        ".rRrrrr...",
        "..rrrrrr..",
        "...rrrrrww",
        "wwwwwwwwww",
        "wwwwwwwwww",
      ],
    ],
  },
  parrot: {
    w: 10, h: 10, anchor: 'bottom',
    palette: { r: '#e0362b', b: '#3fa9ff', o: '#e8871e', k: '#0c0c0c', g: '#2eff70' },
    frames: [
      [
        "....rr....",
        "...rrrr...",
        "...rrkro..",
        "..rrrrrr..",
        ".bbrrrrr..",
        "bbbbrrrr..",
        "..bbrrr...",
        "...rrrr...",
        "..gg.rr...",
        ".gg.......",
      ],
      [
        "....rr....",
        "...rrrr...",
        "...rrkro..",
        "..rrrrrr..",
        "..rrrrrr..",
        "..bbrrrr..",
        ".bbbbrr...",
        "...rrrr...",
        "..gg.rr...",
        ".gg.......",
      ],
    ],
  },
  blaze_rod: {
    w: 8, h: 16, anchor: 'center',
    palette: { g: '#f5c542', G: '#b8860b', o: '#ff8c1a', k: '#5a3a08' },
    frames: [
      [
        "...oo...",
        "..oggo..",
        "..ggGo..",
        "..gGgg..",
        "..ggGg..",
        "..gGgg..",
        "..ggGg..",
        "..oGgo..",
        "..ggGo..",
        "..gGgg..",
        "..ggGg..",
        "..gGgg..",
        "..ggGo..",
        "..oGgo..",
        "..ooo...",
        "...k....",
      ],
    ],
  },
  powerup_sword: {
    w: 14, h: 14, anchor: 'center',
    palette: { d: '#3fd6e0', D: '#2a9aa8', h: '#8a5a3a', H: '#5f3a22', g: '#c9c9c9' },
    frames: [
      [
        "...........dd.",
        "..........ddd.",
        ".........dddd.",
        "........dddd..",
        ".......dddd...",
        "..gg..dddd....",
        "..ggg.ddd.....",
        "...gggdd......",
        "....ggg.......",
        "...hggg.......",
        "..hh..gg......",
        ".hh...........",
        ".Hh...........",
        "..............",
      ],
    ],
  },
  powerup_axe: {
    w: 14, h: 14, anchor: 'center',
    palette: { i: '#c9c9c9', I: '#8f8f8f', h: '#8a5a3a', H: '#5f3a22' },
    frames: [
      [
        "..............",
        "....iii.......",
        "...iiiii......",
        "..iiiiiii.....",
        "..iiIhhii.....",
        "..iiIh.ii.....",
        "...iIh.i......",
        "....hh........",
        "....hh........",
        "....hh........",
        "....hh........",
        "....Hh........",
        "....Hh........",
        "..............",
      ],
    ],
  },
  head_fallback: {
    w: 8, h: 8, anchor: 'center',
    palette: { h: '#4a2f1b', s: '#d8a077', e: '#ffffff', p: '#3d55b8', m: '#8a5a3a' },
    frames: [
      [
        "hhhhhhhh",
        "hhhhhhhh",
        "sshsshss",
        "ssssssss",
        "sepsspes",
        "ssssssss",
        "ssmmmmss",
        "ssssssss",
      ],
    ],
  },
};
