// Core sprites owned by the engine: the crowd runner (BACK view — camera chases
// the crowd) and shop preview body. Skins recolor these via palette override —
// keys: h hair, s skin, t shirt, T shirt-dark, l pants, L pants-dark, b boots.
export const CORE = {
  runner_back: {
    w: 12, h: 18, anchor: 'bottom',
    palette: {
      h: '#4a2f1b', s: '#d8a077', t: '#00afaf', T: '#008f8f',
      l: '#3d55b8', L: '#2e4090', b: '#6e6e6e',
    },
    frames: [
      [
        "...hhhhhh...",
        "...hhhhhh...",
        "...hhhhhh...",
        "...hhhhhh...",
        "...hhhhhh...",
        "....ssss....",
        "..tttttttt..",
        "..tTttttTt..",
        "..tttttttt..",
        "..tTttttTt..",
        "..tttttttt..",
        "..sTttttTs..",
        "...tttttt...",
        "...llLLll...",
        "...llLLll...",
        "...ll..ll...",
        "...bb..bb...",
        "...bb..bb...",
      ],
      [
        "...hhhhhh...",
        "...hhhhhh...",
        "...hhhhhh...",
        "...hhhhhh...",
        "...hhhhhh...",
        "....ssss....",
        "..tttttttt..",
        "..sTttttTt..",
        "..tttttttt..",
        "..tTttttTs..",
        "..tttttttt..",
        "..tTttttTt..",
        "...tttttt...",
        "...llLLll...",
        "...llLLll...",
        "...bb..ll...",
        "...bb..ll...",
        "...bb..bb...",
      ],
    ],
  },
  // Front body for the shop preview (head drawn separately from head_* sprites).
  runner_body_front: {
    w: 12, h: 12, anchor: 'bottom',
    palette: {
      s: '#d8a077', t: '#00afaf', T: '#008f8f',
      l: '#3d55b8', L: '#2e4090', b: '#6e6e6e',
    },
    frames: [
      [
        "..tttttttt..",
        "..tTttttTt..",
        "..tttttttt..",
        "..tTttttTt..",
        "..sTttttTs..",
        "...tttttt...",
        "...llLLll...",
        "...llLLll...",
        "...ll..ll...",
        "...ll..ll...",
        "...bb..bb...",
        "...bb..bb...",
      ],
    ],
  },
  // Villager head: bald brown head, unibrow, dot eyes, long central nose. Shared
  // by every home villager; profession is read from the robe body, not the face.
  head_villager: {
    w: 8, h: 8, anchor: 'center',
    palette: { s: '#a8763f', n: '#8a5f30', w: '#4a3420', k: '#241a10', m: '#7a5228' },
    frames: [
      [
        "ssssssss",
        "ssssssss",
        "swwwwwws",
        "sksnnsks",
        "sssnnsss",
        "sssnnsss",
        "ssmmmmss",
        "ssssssss",
      ],
    ],
  },
  // Villager robe body: crossed arms over a center apron stripe, robe to the feet.
  // Robe colours (r/R/a) are overridden per profession; s = hands.
  villager_body: {
    w: 12, h: 12, anchor: 'bottom',
    palette: { r: '#7a5a3a', R: '#5f4528', a: '#9a7a4a', s: '#a8763f' },
    frames: [
      [
        "..rrrrrrrr..",
        "..rrraarrr..",
        "..rRraarRr..",
        "..rrraarrr..",
        "..rssaassr..",
        "..rssaassr..",
        "..rrraarrr..",
        "..rrraarrr..",
        "..rRraarRr..",
        "..rrraarrr..",
        "..rrrrrrrr..",
        "...RR..RR...",
      ],
    ],
  },
  // Enderman lives in core (End-biome enemy) so the roster works even if a pack fails.
  enderman: {
    w: 14, h: 28, anchor: 'bottom',
    palette: { k: '#1c1c1c', K: '#0e0e0e', p: '#c76bff', P: '#8b3fd6' },
    frames: [
      [
        "...kkkkkkkk...",
        "...kKkkkkKk...",
        "...kkkkkkkk...",
        "...kkkkkkkk...",
        "...pPkkkkPp...",
        "...kkkkkkkk...",
        "...kKkkkkKk...",
        "...kkkkkkkk...",
        "..K..kkkk..K..",
        "..k..kKkk..k..",
        "..k..kkkk..k..",
        "..K..kkKk..K..",
        "..k..kkkk..k..",
        "..k..kKkk..k..",
        "..K..kkkk..K..",
        "..k..kkkk..k..",
        "..k..KkkK..k..",
        ".....kkkk.....",
        "....kk..kk....",
        "....kK..Kk....",
        "....kk..kk....",
        "....kk..kk....",
        "....Kk..kK....",
        "....kk..kk....",
        "....kk..kk....",
        "....kK..Kk....",
        "....kk..kk....",
        "....KK..KK....",
      ],
      [
        "...kkkkkkkk...",
        "...kKkkkkKk...",
        "...kkkkkkkk...",
        "...kkkkkkkk...",
        "...pPkkkkPp...",
        "...kkkkkkkk...",
        "...kKkkkkKk...",
        "...kkkkkkkk...",
        ".K...kkkk...K.",
        ".k...kKkk...k.",
        ".k...kkkk...k.",
        ".K...kkKk...K.",
        ".k...kkkk...k.",
        ".k...kKkk...k.",
        ".K...kkkk...K.",
        ".....kkkk.....",
        ".....KkkK.....",
        ".....kkkk.....",
        "....kk..kk....",
        "....kK..Kk....",
        "....kk..kk....",
        "....kk..kk....",
        "....Kk..kK....",
        "....kk..kk....",
        "....kk..kk....",
        "....kK..Kk....",
        "....kk..kk....",
        "....KK..KK....",
      ],
    ],
  },
  // Cosmetics: cape (palette-swapped per cape def), hat overlays, parrot pet.
  cape: {
    w: 8, h: 9, anchor: 'bottom',
    palette: { c: '#c8322a', C: '#8f1f14' },
    frames: [
      [
        "cccccccc",
        "cCccccCc",
        "cccccccc",
        "cCccccCc",
        "cccccccc",
        "cCccccCc",
        "cccccccc",
        "CcCccCcC",
        ".C.CC.C.",
      ],
      [
        "cccccccc",
        "cCccccCc",
        "cccccccc",
        ".ccccccc",
        ".cCccccC",
        "..cccccc",
        "..cCcccc",
        "..CcCccC",
        "...C.CC.",
      ],
    ],
  },
  hat_crown: {
    w: 10, h: 5, anchor: 'bottom',
    palette: { g: '#f3c53f', G: '#c29222', r: '#e04a3f' },
    frames: [
      [
        ".g..g..g..",
        ".g..g..g..",
        ".gggggggg.",
        ".gGrGGrGg.",
        ".gggggggg.",
      ],
    ],
  },
  hat_pumpkin: {
    w: 10, h: 7, anchor: 'bottom',
    palette: { o: '#e8871e', O: '#b5620f', s: '#4f7a1e' },
    frames: [
      [
        "....ss....",
        ".oooooooo.",
        "oOooooooOo",
        "oooOooOooo",
        "oOooooooOo",
        "oooooooooo",
        ".oooooooo.",
      ],
    ],
  },
  hat_slime: {
    w: 10, h: 6, anchor: 'bottom',
    palette: { g: '#7ee06a', G: '#4fb83f' },
    frames: [
      [
        "..gggggg..",
        ".gggggggg.",
        "gggGggGggg",
        "gggggggggg",
        ".gGggggGg.",
        "..g.gg.g..",
      ],
    ],
  },
  hat_tnt: {
    w: 10, h: 5, anchor: 'bottom',
    palette: { r: '#c8322a', R: '#8f1f14', w: '#e8e0d8', k: '#1a1a1a' },
    frames: [
      [
        ".rrrrrrrr.",
        "rrRrrrrRrr",
        "wwwwwwwwww",
        "wkwwkkwwkw",
        "rrRrrrrRrr",
      ],
    ],
  },
  hat_santa: {
    w: 10, h: 7, anchor: 'bottom',
    palette: { r: '#c8322a', R: '#8f1f14', w: '#ffffff' },
    frames: [
      [
        "..rrr.....",
        ".rrrrr....",
        ".rRrrrr...",
        "..rrrrrr..",
        "...rrrrrww",
        "wwwwwwwwww",
        "wwwwwwwwww",
      ],
    ],
  },
  parrot: {
    w: 10, h: 10, anchor: 'bottom',
    palette: { r: '#e0362b', b: '#3fa9ff', o: '#e8871e', k: '#0c0c0c', g: '#2eff70' },
    frames: [
      [
        "....rr....",
        "...rrrr...",
        "...rrkro..",
        "..rrrrrr..",
        ".bbrrrrr..",
        "bbbbrrrr..",
        "..bbrrr...",
        "...rrrr...",
        "..gg.rr...",
        ".gg.......",
      ],
      [
        "....rr....",
        "...rrrr...",
        "...rrkro..",
        "..rrrrrr..",
        "..rrrrrr..",
        "..bbrrrr..",
        ".bbbbrr...",
        "...rrrr...",
        "..gg.rr...",
        ".gg.......",
      ],
    ],
  },
  blaze_rod: {
    w: 8, h: 16, anchor: 'center',
    palette: { g: '#f5c542', G: '#b8860b', o: '#ff8c1a', k: '#5a3a08' },
    frames: [
      [
        "...oo...",
        "..oggo..",
        "..ggGo..",
        "..gGgg..",
        "..ggGg..",
        "..gGgg..",
        "..ggGg..",
        "..oGgo..",
        "..ggGo..",
        "..gGgg..",
        "..ggGg..",
        "..gGgg..",
        "..ggGo..",
        "..oGgo..",
        "..ooo...",
        "...k....",
      ],
    ],
  },
  powerup_sword: {
    w: 14, h: 14, anchor: 'center',
    palette: { d: '#3fd6e0', D: '#2a9aa8', h: '#8a5a3a', H: '#5f3a22', g: '#c9c9c9' },
    frames: [
      [
        "...........dd.",
        "..........ddd.",
        ".........dddd.",
        "........dddd..",
        ".......dddd...",
        "..gg..dddd....",
        "..ggg.ddd.....",
        "...gggdd......",
        "....ggg.......",
        "...hggg.......",
        "..hh..gg......",
        ".hh...........",
        ".Hh...........",
        "..............",
      ],
    ],
  },
  powerup_axe: {
    w: 14, h: 14, anchor: 'center',
    palette: { i: '#c9c9c9', I: '#8f8f8f', h: '#8a5a3a', H: '#5f3a22' },
    frames: [
      [
        "..............",
        "....iii.......",
        "...iiiii......",
        "..iiiiiii.....",
        "..iiIhhii.....",
        "..iiIh.ii.....",
        "...iIh.i......",
        "....hh........",
        "....hh........",
        "....hh........",
        "....hh........",
        "....Hh........",
        "....Hh........",
        "..............",
      ],
    ],
  },
  head_fallback: {
    w: 8, h: 8, anchor: 'center',
    palette: { h: '#4a2f1b', s: '#d8a077', e: '#ffffff', p: '#3d55b8', m: '#8a5a3a' },
    frames: [
      [
        "hhhhhhhh",
        "hhhhhhhh",
        "sshsshss",
        "ssssssss",
        "sepsspes",
        "ssssssss",
        "ssmmmmss",
        "ssssssss",
      ],
    ],
  },
};
