// Playroom decoration + house-structure sprites (authored in parallel, validated).
export const DECOR = {
  // --- house structure (drawn into the room background, not placeable) ---
  room_window: {
    w: 16, h: 14, anchor: 'center',
    palette: { d: '#5c3a1e', w: '#a9743f', l: '#c9975c', s: '#4cc2ff', b: '#a8e2ff', c: '#ffffff' },
    frames: [[
      ".dddddddddddddd.",
      ".dwwwwwwwwwwwwd.",
      ".dwsssswwsssswd.",
      ".dwsccswwcssswd.",
      ".dwccccwwccsswd.",
      ".dwsssswwsssswd.",
      ".dwwwwwwwwwwwwd.",
      ".dwsssswwsssswd.",
      ".dwsbsswwsbsswd.",
      ".dwbssswwbssswd.",
      ".dwsssswwsssswd.",
      ".dwwwwwwwwwwwwd.",
      "dlllllllllllllld",
      ".dddddddddddddd.",
    ]],
  },
  room_door: {
    w: 14, h: 22, anchor: 'bottom',
    palette: { k: '#2b1a0e', f: '#6b4726', d: '#7a5228', w: '#a97c4a', l: '#c69760', g: '#ffd257' },
    frames: [[
      "kkkkkkkkkkkkkk",
      "kffffffffffffk",
      "kfddddddddddfk",
      "kflwwdlwdlwwfk",
      "kflwwdlwdlwwfk",
      "kflwwdlwdlwwfk",
      "kflwwdlwdlwwfk",
      "kflwwdlwdlwwfk",
      "kflwwdlwdlwwfk",
      "kflwwdlwdlwwfk",
      "kflwwdlwdlwwfk",
      "kflwwdlwdlwwfk",
      "kflwwdlwdggwfk",
      "kflwwdlwdgkwfk",
      "kflwwdlwdlwwfk",
      "kflwwdlwdlwwfk",
      "kflwwdlwdlwwfk",
      "kflwwdlwdlwwfk",
      "kflwwdlwdlwwfk",
      "kflwwdlwdlwwfk",
      "kfddddddddddfk",
      "kkkkkkkkkkkkkk",
    ]],
  },
  // --- placeable decor ---
  room_rug: {
    w: 22, h: 8, anchor: 'bottom',
    palette: { d: '#5b3326', y: '#e6a437', c: '#f4e3c0', r: '#c8402f', f: '#d9c49a' },
    frames: [[
      "....dddddddddddddd....",
      "...dyyyyyyyyyyyyyyd...",
      "..dyccccccccccccccyd..",
      ".fdyccrrccccccrrccydf.",
      "ffdycrrrccrrccrrrcydff",
      "..dyccrrccccccrrccyd..",
      "...dyyyyyyyyyyyyyyd...",
      "....dddddddddddddd....",
    ]],
  },
  room_shelf: {
    w: 16, h: 10, anchor: 'bottom',
    palette: { w: '#b5854f', d: '#4a2f18', r: '#c9453d', b: '#3f7fd0', y: '#e8c34a', g: '#4caf50' },
    frames: [[
      "...........gg...",
      "..........gggg..",
      ".drrbbyyd..gg...",
      ".drrbbyyd.rrrr..",
      ".drrbbyyd.rrrr..",
      ".drrbbyyd..dd...",
      "wwwwwwwwwwwwwwww",
      "dddddddddddddddd",
      "..ww........ww..",
      "..dd........dd..",
    ]],
  },
  room_lamp: {
    w: 10, h: 20, anchor: 'bottom',
    palette: { k: '#2e2418', p: '#6b5a3f', c: '#fff3c9', y: '#f2c75c', w: '#ffdf8a' },
    frames: [[
      "...kkkk...",
      "..kccyyk..",
      ".kcccyyyk.",
      "kccccyyyyk",
      "kccccyyyyk",
      "kkkkkkkkkk",
      "..wwwwww..",
      "....pk....",
      "....pk....",
      "....pk....",
      "....pk....",
      "....pk....",
      "....pk....",
      "....pk....",
      "....pk....",
      "....pk....",
      "....pk....",
      "...kppk...",
      ".kppppppk.",
      "kkkkkkkkkk",
    ]],
  },
  crafting_table: {
    w: 12, h: 12, anchor: 'bottom',
    palette: { h: '#dba14e', b: '#c2893c', B: '#9e6c2f', d: '#6e4824', g: '#3f2712', k: '#2a1b0d' },
    frames: [[
      "khhhghhghhhk",
      "kggggggggggk",
      "kbbbgbbgbbbk",
      "kggggggggggk",
      "kbbbgbbgbbbk",
      "kBBBBBBBBBBk",
      "kddddddddddk",
      ".db.d..d.bd.",
      ".db.d..d.bd.",
      ".db.d..d.bd.",
      ".db......bd.",
      ".dd......dd.",
    ]],
  },
  torch: {
    w: 6, h: 14, anchor: 'bottom',
    palette: { o: '#e8871e', y: '#ffe14d', b: '#8a5a2b', d: '#5a3a1c' },
    frames: [[
      "..oo..",
      ".ooo..",
      ".oyoo.",
      ".oyyo.",
      ".oyyo.",
      ".ooyo.",
      "..oo..",
      "..dd..",
      "..bb..",
      "..bd..",
      "..bb..",
      "..bd..",
      "..bb..",
      "..dd..",
    ]],
  },
  potted_plant: {
    w: 12, h: 12, anchor: 'bottom',
    palette: { g: '#5cbf4a', k: '#3a8a37', o: '#c96a3a', d: '#8f4322', r: '#e08a52' },
    frames: [[
      "...g.gg.g...",
      "..gggggggg..",
      ".gggggggggg.",
      ".gggggggggg.",
      ".gggggggggg.",
      "..gggggggg..",
      "...gkkkkg...",
      ".drrrrrrrrd.",
      "..doooood...",
      "...doood....",
      "...doood....",
      "....dod.....",
    ]],
  },
  painting: {
    w: 12, h: 12, anchor: 'bottom',
    palette: { k: '#3a2412', w: '#a9712e', b: '#4fb8ee', g: '#3fbf4a', y: '#ffd23f' },
    frames: [[
      "kkkkkkkkkkkk",
      "kwwwwwwwwwwk",
      "kwbbbbbbbbwk",
      "kwbbbybbbbwk",
      "kwbbbbbbbbwk",
      "kwbbbbbbbbwk",
      "kwggggggggwk",
      "kwggggggggwk",
      "kwggggggggwk",
      "kwwwwwwwwwwk",
      "kkkkkkkkkkkk",
      "...kk..kk...",
    ]],
  },
  bed: {
    w: 14, h: 9, anchor: 'bottom',
    palette: { k: '#3a2416', w: '#a9722e', r: '#d83b3b', m: '#a82828', p: '#f5f0e6' },
    frames: [[
      "..pppp..rrrr..",
      ".kppppkkrrrrk.",
      ".kpppprrrrrrk.",
      ".krrrrrrrrrmk.",
      ".krrrrrrrrrmk.",
      "kwwwwwwwwwwwwk",
      "kwwwwwwwwwwwwk",
      "kwk......kwk..",
      "kwk......kwk..",
    ]],
  },
  cake: {
    w: 12, h: 8, anchor: 'bottom',
    palette: { k: '#6b3a2a', r: '#e0402f', d: '#a3241a', w: '#fbf1da', c: '#e6d3aa' },
    frames: [[
      ".kkkkkkkkkk.",
      ".krrrrrrrrk.",
      ".krddrrddrk.",
      ".krrrrrrrrk.",
      ".kwwwwwwwwk.",
      ".kwwwwwwwwk.",
      ".kcccccccck.",
      ".kkkkkkkkkk.",
    ]],
  },
};
