// Playroom decoration sprites (authored in parallel, format-validated).
export const DECOR = {
  crafting_table: {
    w: 12, h: 12, anchor: 'bottom',
    palette: { h: '#dba14e', b: '#c2893c', B: '#9e6c2f', d: '#6e4824', g: '#3f2712', k: '#2a1b0d' },
    frames: [[
      "khhhghhghhhk",
      "kggggggggggk",
      "kbbbgbbgbbbk",
      "kggggggggggk",
      "kbbbgbbgbbbk",
      "kBBBBBBBBBBk",
      "kddddddddddk",
      ".db.d..d.bd.",
      ".db.d..d.bd.",
      ".db.d..d.bd.",
      ".db......bd.",
      ".dd......dd.",
    ]],
  },
  torch: {
    w: 6, h: 14, anchor: 'bottom',
    palette: { o: '#e8871e', y: '#ffe14d', b: '#8a5a2b', d: '#5a3a1c' },
    frames: [[
      "..oo..",
      ".ooo..",
      ".oyoo.",
      ".oyyo.",
      ".oyyo.",
      ".ooyo.",
      "..oo..",
      "..dd..",
      "..bb..",
      "..bd..",
      "..bb..",
      "..bd..",
      "..bb..",
      "..dd..",
    ]],
  },
  potted_plant: {
    w: 12, h: 12, anchor: 'bottom',
    palette: { g: '#5cbf4a', k: '#3a8a37', o: '#c96a3a', d: '#8f4322', r: '#e08a52' },
    frames: [[
      "...g.gg.g...",
      "..gggggggg..",
      ".gggggggggg.",
      ".gggggggggg.",
      ".gggggggggg.",
      "..gggggggg..",
      "...gkkkkg...",
      ".drrrrrrrrd.",
      "..doooood...",
      "...doood....",
      "...doood....",
      "....dod.....",
    ]],
  },
  painting: {
    w: 12, h: 12, anchor: 'bottom',
    palette: { k: '#3a2412', w: '#a9712e', b: '#4fb8ee', g: '#3fbf4a', y: '#ffd23f' },
    frames: [[
      "kkkkkkkkkkkk",
      "kwwwwwwwwwwk",
      "kwbbbbbbbbwk",
      "kwbbbybbbbwk",
      "kwbbbbbbbbwk",
      "kwbbbbbbbbwk",
      "kwggggggggwk",
      "kwggggggggwk",
      "kwggggggggwk",
      "kwwwwwwwwwwk",
      "kkkkkkkkkkkk",
      "...kk..kk...",
    ]],
  },
  bed: {
    w: 14, h: 9, anchor: 'bottom',
    palette: { k: '#3a2416', w: '#a9722e', r: '#d83b3b', m: '#a82828', p: '#f5f0e6' },
    frames: [[
      "..pppp..rrrr..",
      ".kppppkkrrrrk.",
      ".kpppprrrrrrk.",
      ".krrrrrrrrrmk.",
      ".krrrrrrrrrmk.",
      "kwwwwwwwwwwwwk",
      "kwwwwwwwwwwwwk",
      "kwk......kwk..",
      "kwk......kwk..",
    ]],
  },
  cake: {
    w: 12, h: 8, anchor: 'bottom',
    palette: { k: '#6b3a2a', r: '#e0402f', d: '#a3241a', w: '#fbf1da', c: '#e6d3aa' },
    frames: [[
      ".kkkkkkkkkk.",
      ".krrrrrrrrk.",
      ".krddrrddrk.",
      ".krrrrrrrrk.",
      ".kwwwwwwwwk.",
      ".kwwwwwwwwk.",
      ".kcccccccck.",
      ".kkkkkkkkkk.",
    ]],
  },
};
