// Item pickups, powerup icons, ally mobs, and shop-avatar heads for Craft Rush.
// Original blocky voxel art -- not derived from any copyrighted texture set.
export const ITEMS = {
  emerald: {
    w: 12, h: 14, anchor: 'center',
    palette: { k:'#063D20', E:'#8FFFC0', e:'#17C964', g:'#0FA355', G:'#0C8A47', d:'#0A6636', w:'#FFFFFF' },
    frames: [
      [
        "....kkkk....",
        "...kEEEEk...",
        "..kEweeeEk..",
        ".kEeegGeeEk.",
        "kEeegGGgeeEk",
        "kEeeGggGeeEk",
        "kEeegGGgeeEk",
        "kEeeGggGeeEk",
        "kdeegGGgeedk",
        ".kdeeGgeedk.",
        "..kdeeeedk..",
        "...kddddk...",
        "....kkkk....",
        ".....kk.....",
      ],
      [
        "....kkkk....",
        "...kEEEEk...",
        "..kEeeeeEk..",
        ".kEeegGeeEk.",
        "kEeegGGgeeEk",
        "kEeeGggGeeEk",
        "kEeegGGgeeEk",
        "kEeeGggGeeEk",
        "kdeegGGgeedk",
        ".kdeeGgewdk.",
        "..kdeeeedk..",
        "...kddddk...",
        "....kkkk....",
        ".....kk.....",
      ],
    ],
  },
  golden_apple: {
    w: 12, h: 14, anchor: 'center',
    palette: { k:'#4a3510', G:'#fff2a8', g:'#f2c94c', d:'#9c6b0e', s:'#5c3a1e', l:'#4fbf3c', w:'#ffffff' },
    frames: [
      [
        ".....ss.....",
        "....sll.....",
        "...kGGGGk...",
        "..kGwGggGk..",
        ".kGggGggggk.",
        "kGggggggggGk",
        "kggggGggddgk",
        "kgdggggGgdgk",
        "kgddggggdggk",
        "kddgggdgddgk",
        ".kdgddgddgk.",
        "..kddgdddk..",
        "...kdddgk...",
        "....kddk....",
      ],
    ],
  },
  tnt_block: {
    w: 14, h: 14, anchor: 'center',
    palette: { k:'#5c0f0f', r:'#cc2b2b', R:'#e2453d', d:'#8a1c1c', w:'#f2ede0', b:'#141414' },
    frames: [
      [
        "kkkkkkkkkkkkkk",
        "krrrrrrRrrRdrk",
        "kdrrrRrRrRrrrk",
        "krrrrrrrrrrrrk",
        "kdrrrrrRrrrrRk",
        "kwbbbwbwbwbbbk",
        "kwwbwwbbwwwbwk",
        "kwwbwwwbbwwbwk",
        "kwwbwwbwbwwbwk",
        "krrrRrrrrrrrRk",
        "kdddrrrRrrdrRk",
        "kRrdRrrrrrrdrk",
        "krrrrrrRrrrrdk",
        "kkkkkkkkkkkkkk",
      ],
    ],
  },
  heart: {
    w: 12, h: 11, anchor: 'center',
    palette: { k:'#5c0f14', r:'#e0293b', R:'#ff7a86', d:'#a3121f' },
    frames: [
      [
        ".kkkk..kkkk.",
        "krRRrrrrrrrk",
        "krRRrrrrrrrk",
        "krRrrrrrrrrk",
        ".krrrrrrrrk.",
        ".krrrrrddrk.",
        "..krrrrddk..",
        "...krrddk...",
        "....kdrk....",
        ".....kk.....",
        ".....kk.....",
      ],
    ],
  },
  arrow: {
    w: 6, h: 14, anchor: 'center',
    palette: { k:'#3a3a3a', g:'#c4c4c4', s:'#7a4a26', S:'#a06835', f:'#f0f0f0', F:'#b0b0b0' },
    frames: [
      [
        "..kk..",
        ".kggk.",
        "kggggk",
        ".kssk.",
        "..ss..",
        "..Ss..",
        "..ss..",
        "..Ss..",
        "..ss..",
        "..ss..",
        ".fssf.",
        "FfssfF",
        ".fssf.",
        "..ss..",
      ],
    ],
  },
  fireball: {
    w: 10, h: 10, anchor: 'center',
    palette: { d:'#7a1f00', O:'#e85d00', o:'#ff7b1a', y:'#ffd23d', Y:'#fff2b0' },
    frames: [
      [
        "...dddd...",
        ".dyooyood.",
        "doOooyOyod",
        "dooYYyoyyd",
        "yooyyOoyyd",
        "doooooOoyd",
        "doooooooOd",
        ".dooooood.",
        "..dOooOd..",
        "...dddd...",
      ],
      [
        "...dddd...",
        ".doOoOood.",
        "doyooooood",
        "dyooyooood",
        "doooYYoood",
        "dyoOyyoooy",
        "dooooooood",
        ".doooyood.",
        "..dooood..",
        "...dddd...",
      ],
    ],
  },
  xp_orb: {
    w: 8, h: 8, anchor: 'center',
    palette: { d:'#4a5e0a', o:'#a4d92c', y:'#d9f24a', Y:'#f4ffb0' },
    frames: [
      [
        "...dd...",
        "..dyod..",
        ".doyood.",
        "dyyYYood",
        "dyoYYyod",
        ".dooood.",
        "..dood..",
        "...dd...",
      ],
      [
        "...dd...",
        "..dyod..",
        ".doooyd.",
        "dooyyoyd",
        "dyoyyood",
        ".dyoyyd.",
        "..dyyd..",
        "...dd...",
      ],
    ],
  },
  potion: {
    w: 10, h: 14, anchor: 'center',
    palette: { k:'#2b1a35', c:'#7a4a26', C:'#5c3616', p:'#8a3fc9', P:'#c68bf5', d:'#5a1f8f', w:'#ffffff' },
    frames: [
      [
        "....CC....",
        "....CC....",
        "...kppk...",
        "...kppk...",
        "..kppppk..",
        ".kPpppppk.",
        ".kwpppppk.",
        ".kPpppppk.",
        ".kPpppppk.",
        ".kppppddk.",
        ".kppppddk.",
        "..kpppdk..",
        "...kppk...",
        "...kkkk...",
      ],
    ],
  },
  powerup_triple: {
    w: 14, h: 14, anchor: 'center',
    palette: { s:'#3d6d99', S:'#5c94c9', h:'#ffe066', d:'#1f3a52' },
    frames: [
      [
        "..............",
        "......hhh.....",
        ".......hs.....",
        ".hhh...Ss..hhh",
        "..hss..ss..sh.",
        "...ss..ss..sS.",
        "....sS.sS.Ss..",
        "....Ss.SS.ss..",
        ".....SssSss...",
        ".....SssssS...",
        "......ssss....",
        "......ssss....",
        "......ddd.....",
        "......ddd.....",
      ],
    ],
  },
  powerup_rapid: {
    w: 14, h: 14, anchor: 'center',
    palette: { k:'#3a3a3a', g:'#c4c4c4', s:'#7a4a26', S:'#a06835', f:'#f0f0f0', F:'#b0b0b0', y:'#ffd23d', Y:'#fff6c2' },
    frames: [
      [
        "........kk....",
        ".......kggk...",
        "......kggggk..",
        ".......kssk...",
        "........ss....",
        "...Yy...Ss....",
        "..Yy.y..ss....",
        ".Yy.y...Ss....",
        ".y.y....ss....",
        "y.yY....ss....",
        ".yY....fssf...",
        ".Y....FfssfF..",
        "Y......fssf...",
        "........ss....",
      ],
    ],
  },
  powerup_power: {
    w: 14, h: 14, anchor: 'center',
    palette: { k:'#3a3a3a', g:'#c4c4c4', s:'#7a4a26', S:'#a06835', f:'#f0f0f0', F:'#b0b0b0', r:'#e2453d', R:'#ff8079' },
    frames: [
      [
        "........kk....",
        ".......kggk...",
        "......kggggk..",
        ".......kssk...",
        "...r....ss....",
        "..rRr...Ss....",
        ".rR.Rr..ss....",
        ".rR.Rr..Ss....",
        "rR...Rr.ss....",
        "........ss....",
        ".......fssf...",
        "......FfssfF..",
        ".......fssf...",
        "........ss....",
      ],
    ],
  },
  chest: {
    w: 16, h: 14, anchor: 'center',
    palette: { k:'#2b1a0d', b:'#8a5a2e', B:'#b07a3e', d:'#5c3a1a', g:'#e8c14a', G:'#fff0a0', o:'#8a6110' },
    frames: [
      [
        "...kBBBBBBBBk...",
        ".kBBBBBBBBBBBBk.",
        "kbbdbbGGGGbbbbbk",
        "kkkkkkggggkkkkkk",
        "kbdbbbgoogbbBBBk",
        "kbbbbbgoogbbBbBk",
        "kbbbbbgoogBbBbbk",
        "kbbbbdbbbbbbbbbk",
        "kbbbBdbbBbdbbbBk",
        "kBbdbbbbbdbbbbbk",
        "kbbbbBBbbbbbbbbk",
        "kbbbbbbbbBbdbbdk",
        "kddddddddddddddk",
        "kkkkkkkkkkkkkkkk",
      ],
    ],
  },
  iron_golem: {
    w: 22, h: 30, anchor: 'bottom',
    palette: { k:'#2b2f33', i:'#9aa0a6', I:'#c7ccd1', d:'#5c6166', e:'#141414', r:'#c62828', v:'#4a7c2e' },
    frames: [
      [
        ".......kkkkkkkk.......",
        ".......kiiiiiik.......",
        ".......kdeiieik.......",
        ".......kiiiiiIk.......",
        ".......kieeeeik.......",
        ".......kiiIdiik.......",
        "kkkkkkkiiiiiiiikkkkkkk",
        "kiIdiiIIIIiiiiiiiIIiik",
        "kiIiiiiiiiidiiiiiiiiik",
        "kiiiidiiiiiiiiiiIddiik",
        "kiiiiiiiiiIiiiiiiiiIik",
        "kiiiiiiidiiiiIiiidiiik",
        "kiiiiidvriIiiiIIIiiiik",
        "kIiiiIiviiiiiiiiiidIik",
        "kiIiiiiiiiiIiiiiiiiiik",
        "kiiiiIiiIiiiiiiidiiiik",
        "kiiiiiiidiiiidiIiiiiik",
        "kIiiiidiiiiIidiiididik",
        "kiiiiiiiiIiiiiiiiiiIik",
        "kiiikIiiiiiIiiiiikiiIk",
        "kiik.kiiiiiiiiiik.kddk",
        "kddk.kiiiIiiiIiik.kddk",
        "kddk.kiiiiiiiiiik.kkkk",
        "kkkk.kiiiikkiiiIk.....",
        "......kiik..kiik......",
        "......kdIk..kiik......",
        "......kIik..kiik......",
        "......kiik..kiik......",
        "......kiik..kkkk......",
        "......kkkk............",
      ],
      [
        ".......kkkkkkkk.......",
        ".......kiiiIiik.......",
        ".......kieIieik.......",
        ".......kiiiiiik.......",
        ".......kieeeeik.......",
        ".......kiiiiiik.......",
        "kkkkkkkiiiiIiiikkkkkkk",
        "kiiiiiiiIiiIiIiidiiIik",
        "kiiiiiiiiiiidiIiidiiik",
        "kiiiiiiiiiiIiiiiiiiiik",
        "kiIiiiiIidiiidiiiiiiik",
        "kiiiiiiIiIdiiiIiiiiiik",
        "kidiiiivrIiiiiiiiiiiik",
        "kIiiIiivIiiiiIiidiiiik",
        "kiiiIiiiiidiiiiidiIiik",
        "kdiiiiiiIiiiiiIIiiiiik",
        "kiiiiiiiIiiiiIiiiiiiik",
        "kiIiIidiiiiiiiIiiiiiIk",
        "kiiiidiiiIiiiiiiIiiiik",
        "kdiikiiiidIiIiiiikiiik",
        "kddk.kiiIiiiiiiik.kiik",
        "kddk.kiiiiiiiiiik.kddk",
        "kkkk.kiiiiiiiiiik.kddk",
        ".....kiiiikkiiiik.kkkk",
        "......kiik..kiik......",
        "......kidk..kiik......",
        "......kIik..kIik......",
        "......kIik..kiik......",
        "......kkkk..kiik......",
        "............kkkk......",
      ],
    ],
  },
  wolf: {
    w: 18, h: 14, anchor: 'bottom',
    palette: { k:'#2b2b2e', g:'#8a8f94', G:'#e4e7ea', d:'#5a5f66', r:'#c62828', e:'#141414' },
    frames: [
      [
        "..................",
        "..................",
        ".kk..kk...........",
        "kggkkggk.......kkk",
        "kgdggggk.......kgk",
        "kGeGgggk.......kgk",
        "kgggdgggkkkkkkkggk",
        "kGGgggggggggggggkk",
        "keGGGgrrrggggGgk..",
        "kkkkkkggkddkggkk..",
        "......kk.kk.kk....",
        "......kk.kk.kk....",
        "......kk.kk.kk....",
        "......kk..........",
      ],
      [
        "..................",
        "..................",
        ".kk..kk...........",
        "kggkkggk..........",
        "kgggggGk.......kkk",
        "kgeggggk.......kgk",
        "kgGgGgggkkkkkkkggk",
        "kGGgGgGggggggdgggk",
        "keGgggrrrgggggggkk",
        "kkkkkkgGkddkGgkk..",
        "......kk.kk.kk....",
        "......kk.kk.kk....",
        "......kk.kk.kk....",
        "............kk....",
      ],
    ],
  },
  snow_golem: {
    w: 14, h: 24, anchor: 'bottom',
    palette: { S:'#4f6b8a', w:'#eef3f7', W:'#ffffff', n:'#c7d6e3', o:'#e8842a', O:'#ffb15c', p:'#8a4a12', k:'#1a1006', b:'#5c3a1e' },
    frames: [
      [
        ".....pppp.....",
        "...ppoooopp...",
        "..pokkookkop..",
        "..pokooookop..",
        "...pkkkkkkp...",
        "....poOoop....",
        "....SwwwwS....",
        "...SwwwwWwS...",
        "..SwwwwWwwwS..",
        "bSwwwwWwwwwWSb",
        ".bwnwwwwwwwwb.",
        ".SWwwwWwwwwwS.",
        "..SwwwWwwwwS..",
        "...SwwwwwwS...",
        "....SwwwwS....",
        "...SwwwwwwS...",
        "..SwwwwwwwwS..",
        ".SwwwwwwWwwwS.",
        "SwwwwwwwWwwwwS",
        "SwwwwwwwwwwwwS",
        "SwwwwWwwwwWwwS",
        ".SwwwwwwwnWwS.",
        "..SWwwwwwwwS..",
        "...SSSSSSSS...",
      ],
      [
        ".....pppp.....",
        "...pppooOpp...",
        "..pokkoOkkop..",
        "..pokooOokop..",
        "...pkkkkkkp...",
        "....poooop....",
        "....SwWWwS....",
        "...SWwwwwwS...",
        "..SwwnwwwwwS..",
        ".SwwwwwwwwWwS.",
        ".bwwwwwwwwwwb.",
        "bSwwwwwwwwwwSb",
        "..SwwWwwwWwS..",
        "...SWwwWwwS...",
        "....SwwwwS....",
        "...SwnwwwwS...",
        "..SwwwwwwwwS..",
        ".SwwwwwwwwwwS.",
        "SwwwwwwwwwwwwS",
        "SwwwwwwwwwwwwS",
        "SwwwwwwwwwwwWS",
        ".SnWwwwwwwwwS.",
        "..SwwwwwwwwS..",
        "...SSSSSSSS...",
      ],
    ],
  },
  head_steve: {
    w: 8, h: 8, anchor: 'center',
    palette: { h:'#4a2f1b', s:'#d8a077', e:'#ffffff', p:'#2a5fd0', m:'#8a5a3a' },
    frames: [
      [
        "hhhhhhhh",
        "hhhhhhhh",
        "sshsshss",
        "ssssssss",
        "sepsspes",
        "ssssssss",
        "ssmmmmss",
        "ssssssss",
      ],
    ],
  },
  head_alex: {
    w: 8, h: 8, anchor: 'center',
    palette: { h:'#cc6b1f', s:'#f0c9a0', e:'#ffffff', p:'#2e9e4f', m:'#a06840' },
    frames: [
      [
        "hhhhhhhh",
        "hhhhhhhh",
        "sshsshss",
        "ssssssss",
        "sepsspes",
        "ssssssss",
        "ssmmmmss",
        "ssssssss",
      ],
    ],
  },
  head_zombie: {
    w: 8, h: 8, anchor: 'center',
    palette: { g:'#3d8a3d', G:'#2a5f2a', k:'#0a1408', m:'#1a2e10' },
    frames: [
      [
        "gggggggg",
        "gGggGggg",
        "gggggggg",
        "gkkggkkg",
        "gGggGggg",
        "gggggggg",
        "gGmmmmGg",
        "gggggggg",
      ],
    ],
  },
  head_skeleton: {
    w: 8, h: 8, anchor: 'center',
    palette: { b:'#e8e4d4', B:'#b5b0a0', k:'#0a0a0a' },
    frames: [
      [
        "bbbbbbbb",
        "bBbbbBbb",
        "bbbbbbbb",
        "bkkbbkkb",
        "bbbkkbbb",
        "bBbbbbBb",
        "bkbkbkbb",
        "bbbbbbbb",
      ],
    ],
  },
  head_enderman: {
    w: 8, h: 8, anchor: 'center',
    palette: { k:'#0a0a0d', K:'#1a1420', p:'#b23dff', P:'#e8b8ff' },
    frames: [
      [
        "kkkkkkkk",
        "kKkkkKkk",
        "kkkkkkkk",
        "kppkkppk",
        "kPPkkPPk",
        "kkkkkkkk",
        "kKkkkkKk",
        "kkkkkkkk",
      ],
    ],
  },
  head_piglin: {
    w: 8, h: 8, anchor: 'center',
    palette: { h:'#e8c14a', s:'#e08a9a', S:'#c96a7a', e:'#2a1010', t:'#f5f0e0', m:'#3a1a10' },
    frames: [
      [
        "hhhhhhhh",
        "hhhhhhhh",
        "sshsshss",
        "ssssssss",
        "sesssess",
        "ssSsSsss",
        "sttmmtts",
        "ssssssss",
      ],
    ],
  },
  head_creeper: {
    w: 8, h: 8, anchor: 'center',
    palette: { a:'#66d94f', g:'#4fbf3c', G:'#3da52e', k:'#0f1a0c' },
    frames: [
      [
        "gagGgagg",
        "agGggagG",
        "gkkggkkg",
        "GkkggkkG",
        "gggkkggg",
        "ggkkkkgg",
        "gkkggkkg",
        "ggkggkgg",
      ],
    ],
  },
};
