export const SCENERY = {
  oak_tree: {
    w: 24, h: 32, anchor: 'bottom',
    palette: { a:'#7fd957', g:'#4fa832', G:'#3d8a26', d:'#276318', b:'#8a5a2b', B:'#6b4423', k:'#4a2f18' },
    frames: [
      [
        "........dGggaggd........",
        "......dggGGgggGggd......",
        "....daggGGgggGgGaggd....",
        "...daaGgaGgggGggGgggd...",
        "..dggggagggggGaggGgggd..",
        ".dgggggggGGggggGgggggad.",
        ".dggggaggGggggggggGggGd.",
        "dggggggggGaGgggggaggGGGd",
        "dgaGggGGgGaggggGggGGggGd",
        ".dggGGGgGgggagggagggggd.",
        ".dGaggagagggaGgGgggGggd.",
        "..dggggGggGGgaggggGGgd..",
        "..dgggGggggggggagGGgGd..",
        "...dgggggaggggGgGGGgd...",
        "....dgggggggaGaggggd....",
        ".....daggGgGGgGaggd.....",
        "......dGGakBBkgGgd......",
        ".......dgkkkBkBgd.......",
        ".........bkbbkB.........",
        ".........bkBBkB.........",
        ".........bkBBkB.........",
        ".........bkBkkk.........",
        ".........bkBBkb.........",
        ".........bkBBkk.........",
        ".........bkBBkB.........",
        ".........bkBBkB.........",
        ".........bkBBkB.........",
        ".........bkBBkB.........",
        ".........bkBBkB.........",
        ".........bkBBkB.........",
        ".........bkBBkB.........",
        ".........bkBBkB.........",
      ],
    ],
  },
  birch_tree: {
    w: 24, h: 32, anchor: 'bottom',
    palette: { a:'#c6e86b', g:'#9fcf4f', G:'#7fb23a', d:'#4f7a22', w:'#f2f2e6', n:'#d8d8c8', k:'#2a2a22' },
    frames: [
      [
        ".........dggggd.........",
        ".......dggGgggGad.......",
        ".....dGggGggggGGgGd.....",
        "...dGaGggggggggaggggd...",
        "..daaaGggggggGGggggGgd..",
        ".dgaGaggGaGGgGggGgGgGgd.",
        ".dGaggagGgggGgGagaaGGgd.",
        "dagggggggGGggaGggGggggGd",
        "dGgagaggaGgGagggagGGagGd",
        ".dGggGggggggGGGgggGgggd.",
        "..dagGgggggggggggggggd..",
        "..dggggGgggggggggGgGgd..",
        "...dgaggggaGagGGggggd...",
        "....dagGggggggaGgggd....",
        ".....dggaGgaGgggagd.....",
        "......dggGGgGggagd......",
        "......dGGgwwwnGgad......",
        "........GGkwwwgg........",
        "..........wwww..........",
        "..........nwkw..........",
        "..........nwnk..........",
        "..........wwwn..........",
        "..........nkwn..........",
        "..........wwnw..........",
        "..........nwwk..........",
        "..........knww..........",
        "..........wwww..........",
        "..........knww..........",
        "..........wwww..........",
        "..........wwkw..........",
        "..........wwkw..........",
        "..........nkww..........",
      ],
    ],
  },
  spruce_tree: {
    w: 20, h: 36, anchor: 'bottom',
    palette: { a:'#4f9a4a', g:'#2f6b34', G:'#1f4d24', d:'#123018', b:'#6b4423', k:'#4a2f18' },
    frames: [
      [
        ".........dd.........",
        ".........dd.........",
        "........dGgd........",
        "........dggd........",
        ".......dGgggd.......",
        ".......dgGGad.......",
        "......dgGgGGGd......",
        "........dggd........",
        "........dggd........",
        ".......dGagGd.......",
        ".......dgaGgd.......",
        "......dGgggagd......",
        "......dGGgGgGd......",
        ".....dggggggGgd.....",
        ".....dgGgggaggd.....",
        "....dggGGggggggd....",
        ".......dGgggd.......",
        "......dGGagagd......",
        "......daGGggad......",
        ".....dggggggggd.....",
        ".....dggaGgGGgd.....",
        "....dgggGGagGGad....",
        "....dggggGgggGGd....",
        "...dgggggggagGgGd...",
        "...dggGggggGgggGd...",
        "..dGGGgGggGgagGGGd..",
        "......daggGggd......",
        ".....dggGgGgGgd.....",
        "....dGgaGgagaggd....",
        "....dgGggggagggd....",
        "...dGggaagGGGgggd...",
        "..dgGgggggGGgGgggd..",
        ".dgGggggGgggggggggd.",
        "........bkkb........",
        "........kkbb........",
        "........bkbb........",
      ],
    ],
  },
  snowy_spruce: {
    w: 20, h: 36, anchor: 'bottom',
    palette: { a:'#4f9a4a', g:'#2f6b34', G:'#1f4d24', d:'#123018', b:'#6b4423', k:'#4a2f18', s:'#f2f7fa', S:'#cfe0e8' },
    frames: [
      [
        ".........dd.........",
        ".........dd.........",
        "........dggd........",
        "........dGgd........",
        ".......dGgGgd.......",
        ".......dGgggd.......",
        "......dgggGggd......",
        "........dssd........",
        "........dsSd........",
        ".......dGggGd.......",
        ".......daagad.......",
        "......dggagGGd......",
        "......dgggggGd......",
        ".....dggGgGGggd.....",
        ".....dgGggggGgd.....",
        "....dGgggggggGGd....",
        ".......dsssSd.......",
        "......dSsSsSSd......",
        "......dGgggggd......",
        ".....dggGaaaggd.....",
        ".....dgGGgggggd.....",
        "....dGggaggGgGgd....",
        "....dgggGgGGgGgd....",
        "...dggGggGGGgGggd...",
        "...dgGgggggggaGGd...",
        "..dGgagGgGagggGGGd..",
        "......dsssssSd......",
        ".....dssssssssd.....",
        "....daggGaGgggGd....",
        "....dgggaGgggaGd....",
        "...dggaggGGgggagd...",
        "..dggaGggGGGgggggd..",
        ".dGgggGgGggGgGggggd.",
        "........bkkb........",
        "........kkbb........",
        "........bkbb........",
      ],
    ],
  },
  cactus: {
    w: 12, h: 24, anchor: 'bottom',
    palette: { g:'#4a9c3f', G:'#357a2d', a:'#6fc95c', d:'#1f4a1a', s:'#e8e8c8' },
    frames: [
      [
        ".....dd.....",
        "....dGad....",
        "....dGad....",
        "....dGgd....",
        "....dGgd....",
        "....dGad.dG.",
        "....dGad.dG.",
        "....dGgd.dG.",
        "....dGgd.dG.",
        ".dG.dGgd.ds.",
        ".dG.dGgd.dG.",
        ".dG.dGgaggG.",
        ".dG.dGsgaaG.",
        ".ds.dGgd....",
        ".dG.dGgd....",
        ".dGgsGgd....",
        ".dGggGgd....",
        "....dGgd....",
        "....dGgd....",
        "....dGgd....",
        "....dGgd....",
        "....dGgd....",
        "....dGsd....",
        "....dGgd....",
      ],
    ],
  },
  dead_bush: {
    w: 12, h: 12, anchor: 'bottom',
    palette: { b:'#8a5a2b', B:'#6b4423', k:'#3a2412' },
    frames: [
      [
        "............",
        "............",
        ".......b....",
        "..k....B.b..",
        "...bb..bb...",
        "...bb..bb...",
        "..b.b.BB....",
        "...b.Bb..b..",
        "....BbBbb...",
        ".....Bb.....",
        ".....bB.....",
        ".....bB.....",
      ],
    ],
  },
  red_mushroom: {
    w: 16, h: 16, anchor: 'bottom',
    palette: { r:'#d1382a', R:'#952417', h:'#ef6a52', w:'#f5f0e0', W:'#d8d8d0', s:'#f0e6c8', S:'#cbb88f', k:'#5a140d', d:'#3a0c08' },
    frames: [
      [
        "......dhrd......",
        "....dRrwrrrd....",
        "..drrrrrWrrrrd..",
        ".dRwrrRrrrrwRrd.",
        "drrrWrrwrrRrWRrd",
        "drwrRwrRWrRrrwrd",
        ".drWrrWrrwrrRrd.",
        "..dRrrrrRrWRrd..",
        "...dkkkkkkkkd...",
        "......ksSk......",
        "......Ssss......",
        "......Ssss......",
        "......Ssss......",
        "......SsSs......",
        "......SSSs......",
        "......Ssss......",
      ],
    ],
  },
  crimson_fungus: {
    w: 16, h: 20, anchor: 'bottom',
    palette: { r:'#7a1f2b', R:'#4d1119', h:'#a83347', o:'#ff8c3c', O:'#cc5f22', s:'#caa0a8', S:'#8a6268', k:'#2a0a10', d:'#200609' },
    frames: [
      [
        "......drrd......",
        "....drhoOrhd....",
        "..drhRrrrrhrRd..",
        ".droOrhrrrrRoOd.",
        "drRRrRrrrrRhRRrd",
        "drRrroOrRrrrrrrd",
        "dRoORrrrrroOroOd",
        ".drRRrrrrRRRrRd.",
        "..droORroORrRd..",
        "...dhRrrrrrod...",
        "....dRRRrhrd....",
        "....dkkkkkkd....",
        "......kssk......",
        "......ssss......",
        "......ssss......",
        "......Soss......",
        "......ssss......",
        "......Ssss......",
        "......ssOs......",
        "......ssss......",
      ],
    ],
  },
  warped_fungus: {
    w: 16, h: 20, anchor: 'bottom',
    palette: { r:'#1f8a72', R:'#12594a', h:'#52c9a8', o:'#ff8c3c', O:'#cc5f22', s:'#6f9d92', S:'#4a6b62', k:'#0a2a22', d:'#06140f' },
    frames: [
      [
        "......dhrd......",
        "....dRroOhRd....",
        "..dRRRrrrrhRhd..",
        ".dRoORrrrrrRoOd.",
        "drrhRhrRRhrrrrhd",
        "dRhRroORrrrrrRRd",
        "droOrhRrrroOroOd",
        ".dhrrhrhrrrrrrd.",
        "..droOhRoORrrd..",
        "...drrrhrhRod...",
        "....drhrrhrd....",
        "....dkkkkkkd....",
        "......kssk......",
        "......ssss......",
        "......ssss......",
        "......soss......",
        "......sssS......",
        "......sSss......",
        "......ssOs......",
        "......ssss......",
      ],
    ],
  },
  end_pillar: {
    w: 12, h: 36, anchor: 'bottom',
    palette: { c:'#2b1a33', C:'#1a0f20', h:'#3f2a4a', k:'#10081a', p:'#ff6fd8', P:'#c73fae', w:'#ffd6f5' },
    frames: [
      [
        "............",
        ".....PP.....",
        "....PppP....",
        "...PwpppP...",
        "...wpPwPP...",
        "..PwpwpppP..",
        "...PwpPpP...",
        "...PwpPPP...",
        "....PppP....",
        ".....PP.....",
        "............",
        "..kcccccck..",
        "..kcccccck..",
        "...kCCcck...",
        "...kcCcck...",
        "...kcCcck...",
        "...kcCcck...",
        "...khCcck...",
        "...kcCcck...",
        "...kcCCck...",
        "...kCCcck...",
        "...kcCcck...",
        "...kcCcck...",
        "...kcCcck...",
        "...kcCChk...",
        "...kcCCck...",
        "...kcCcCk...",
        "...kCCcCk...",
        "...kcCcck...",
        "...kcCcck...",
        "...kcCcCk...",
        "...kcCcCk...",
        "...kcCcck...",
        "...kcCchk...",
        "...kcCcCk...",
        "...kCCcCk...",
      ],
    ],
  },
  fence: {
    w: 16, h: 12, anchor: 'bottom',
    palette: { b:'#8a5a2b', B:'#6b4423', h:'#a97a44', k:'#4a2f18' },
    frames: [
      [
        "..h..........h..",
        ".kh..........hk.",
        ".kb..........bk.",
        ".kbBBBBBBBBBBbk.",
        ".kbkbbhbhbbbkbk.",
        ".kb..........bk.",
        ".kB..........bk.",
        ".kbkbbhhbbbbkbk.",
        ".kbBBBBBBBBBBBk.",
        ".kb..........bk.",
        ".kb..........bk.",
        ".kb..........bk.",
      ],
    ],
  },
  flowers: {
    w: 12, h: 8, anchor: 'bottom',
    palette: { g:'#3d8a26', G:'#2b6318', e:'#3d8a26', r:'#d1382a', k:'#3a0c08', y:'#f0c419' },
    frames: [
      [
        "............",
        "...r....y...",
        "..rkr..yyy..",
        "...r....e...",
        "...e....e...",
        "...e....e...",
        ".G.eG.G.eGG.",
        "gggggggggggg",
      ],
    ],
  },
  pumpkin: {
    w: 14, h: 12, anchor: 'bottom',
    palette: { o:'#e07a1e', O:'#a85510', h:'#f5a441', d:'#5c2f08', e:'#4a7a2e', E:'#2f5a1a' },
    frames: [
      [
        "......Ee......",
        "......ee......",
        "....dOOoOd....",
        "..dhhOooOood..",
        ".dOhhOooOooOd.",
        "doOhhOooOooOod",
        "doOOoOooOooOod",
        "doOooOooOooOod",
        ".dOooOooOoOOd.",
        "..doOOooOood..",
        "...doOooOod...",
        "....dOooOd....",
      ],
    ],
  },
  hay_bale: {
    w: 16, h: 14, anchor: 'bottom',
    palette: { y:'#d9a441', Y:'#b8842e', h:'#f0c469', s:'#6b4423', S:'#4a2f18', d:'#6b4423' },
    frames: [
      [
        "...dyhyyyyhhd...",
        ".SsyhyYhYyyyySs.",
        "dyssyYyyyyyyssyd",
        "dYySsYyYyYYssYyd",
        "dYYYssYYYYsSYYYd",
        "dyyyySsyyssYYYyd",
        "dyyyYyssSshyyyyd",
        "dyYyyySsssYyyYyd",
        "dyhYySSYyssyyyyd",
        "dYYYssYYYYssYYYd",
        "dyhsSyyyyyySsYhd",
        "dYssyyyyyyyyssyd",
        ".ssyyyyyyYYyyss.",
        "...dyyyyyyyyd...",
      ],
    ],
  },
  village_house: {
    w: 36, h: 32, anchor: 'bottom',
    palette: { r:'#7a3226', R:'#4f1f18', h:'#a8523f', e:'#c9924f', d:'#2b0f0a', w:'#c9a15a', W:'#a8823e', p:'#7a5a2e', c:'#8a8a8a', C:'#5c5c5c', l:'#adadad', o:'#6b4423', O:'#4a2f18', n:'#d9b23c', f:'#6b4423', g:'#a8d8e8', G:'#6fb3cc' },
    frames: [
      [
        "................drhd................",
        "..............drrrrhhd..............",
        "............dRRRRRRRRRRd............",
        "..........dRRRRRRRRRRRRRRd..........",
        "........drrrrrrrrrrrrrrrrrrd........",
        "......dRRRRRRRRRRRRRRRRRRRRRRd......",
        "....dRRRRRRRRRRRRRRRRRRRRRRRRRRd....",
        "..dRRrhrrrRRrrrrrrrrRrrhrhrrrrrrhd..",
        ".drrhrrrrrrrrRrrhrrRRrrRrrrrrrrrrhd.",
        ".deeeeeeeeeheeeeeeeheeeeeereeeeeeed.",
        "....pppppppppppppppppppppppppppp....",
        "....pwwwpWwwppwWpWwwpwwwpWwWpwWp....",
        "....pwwWpwwwpWwWpwwwpwpppwwwpwwp....",
        "....pwwwffffpwwwppwwpwWpffffpwwp....",
        "....pwwwffGfpwwwpwWwpwpwffgfpwwp....",
        "....pwwwffffpwwwpwwwpwwwffffpwwp....",
        "....ppwwffgfpwwwpwwwpwWwffgfpwwp....",
        "....pwWwffffpwwWpwwwpwWWffffpwwp....",
        "....pwwwpWwWpWwwOooOpwWWpWwWpwwp....",
        "....pwwwpwwwpWwwoOOopwwwpWwwpwWp....",
        "....pWwwpwwwpwwWoOOopwwppWwWpwwp....",
        "....pwwwpwwwpwwwoOnopwwwpwwwpwwp....",
        "....pwWwpwwwpwwwoOOopwwwpWwppwWp....",
        "....pwwwpwwwpwwwooooppWwpwpwpwwp....",
        "...CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC...",
        "...ClllclcclccClCllcclCclCCCcCcCC...",
        "...CCccccclcccclcccClcCcCCCCclCcC...",
        "...CCCccCcClllccCClllCcCClcCccclC...",
        "...CllcccCCcClccCCcCccccCCCllCclC...",
        "...CCccclcCCCCcCccccccccCCCCcCCcC...",
        "...CcCclCCCCllclccccCccccCcCccCcC...",
        "...CccCllClllCCcllCccCCCCcCcclCCC...",
      ],
    ],
  },
  basalt_pillar: {
    w: 12, h: 30, anchor: 'bottom',
    palette: { b:'#4a4a52', B:'#2e2e34', h:'#6a6a74', k:'#1a1a1e', t:'#7a7a86' },
    frames: [
      [
        "..khhththk..",
        ".kttthttthk.",
        "..khBBbBhk..",
        "..khBbbBhk..",
        "..khBbbBhk..",
        "..khBbbBhk..",
        "..khBbbBhk..",
        "..khBbbBhk..",
        "..khBbbBhk..",
        "..kkkkkkkk..",
        "..khBbbBhk..",
        "..khBbbBhk..",
        "..khBbbBhk..",
        "..khBbBBhk..",
        "..khBbbBhk..",
        "..khBbbBhk..",
        "..khBbbBhk..",
        "..khBbbBhk..",
        "..kkkkkkkk..",
        "..khBbBBhk..",
        "..khBBbBhk..",
        "..khBBbBhk..",
        "..khBbbBhk..",
        "..khBbbBhk..",
        "..khBbBBhk..",
        "..khBhbBhk..",
        "..kkkkkkkk..",
        "..khBbbBhk..",
        "..khBbbBhk..",
        "..khBbbBhk..",
      ],
    ],
  },
  cloud: {
    w: 24, h: 10, anchor: 'center',
    palette: { w:'#f7f9fc', h:'#ffffff', s:'#cdd6e0', S:'#a9b6c4', d:'#b7c2cf' },
    frames: [
      [
        ".....dwwd......dwwd.....",
        "....dwwwwd.dd.dwwwwd....",
        "..dwwwwwwwwhwwwwwwwwwd..",
        ".dwwwwwwwwwwwwwwwwwwwhd.",
        "dwwwhwwwwwwwhwwhwwhwwwwd",
        "dwwwwhwwwwwwwwwwwwwhwwwd",
        ".dssSSssssSSsssssSSSSsd.",
        "..dsssssSsssSSSSsssssd..",
        "....dSSssssSsSsssssd....",
        "......dssssSSsssSd......",
      ],
    ],
  },
  nether_brick_pillar: {
    w: 12, h: 30, anchor: 'bottom',
    palette: { d: '#3a1218', b: '#4e1a22', m: '#2a0d12', g: '#6e2028' },
    frames: [
      [
        "..gggggggg..",
        "..gbbbbbbg..",
        "..bbmbbmbb..",
        "..bbbbbbbb..",
        "..mbbmbbmb..",
        "..bbbbbbbb..",
        "..bmbbmbbb..",
        "..bbbbbbbb..",
        "..bbmbbmbb..",
        "..bbbbbbbb..",
        "..mbbmbbmb..",
        "..bbbbbbbb..",
        "..bmbbmbbb..",
        "..bbbbbbbb..",
        "..bbmbbmbb..",
        "..bbbbbbbb..",
        "..mbbmbbmb..",
        "..bbbbbbbb..",
        "..bmbbmbbb..",
        "..bbbbbbbb..",
        "..bbmbbmbb..",
        "..bbbbbbbb..",
        "..mbbmbbmb..",
        "..bbbbbbbb..",
        "..bmbbmbbb..",
        "..bbbbbbbb..",
        "..bbmbbmbb..",
        "..dddddddd..",
        "..dggggggd..",
        "..dddddddd..",
      ],
    ],
  },
  sculk_sensor: {
    w: 16, h: 16, anchor: 'bottom',
    palette: { k: '#0a1416', d: '#16303a', v: '#0f2228', c: '#2fd6d6', C: '#aeffff' },
    frames: [
      [
        "................",
        "................",
        "................",
        "................",
        ".....C..C..C....",
        ".....c..c..c....",
        ".....c..c.Cc....",
        ".....cC.c..c....",
        ".....c..c..c....",
        ".....c..c..c....",
        "..kkkkkkkkkkkk..",
        "..kdddddddvddk..",
        "..kdvddddddddk..",
        "..kdddddvddddk..",
        "..kddddddddddk..",
        "..kkkkkkkkkkkk..",
      ],
    ],
  },
  sculk_shrieker: {
    w: 16, h: 12, anchor: 'bottom',
    palette: { k: '#0a1416', d: '#16303a', t: '#20454f', c: '#2fd6d6', C: '#aeffff' },
    frames: [
      [
        "................",
        "................",
        ".kkkkkkkkkkkkkk.",
        ".kddddddddddddk.",
        ".kddttttttttddk.",
        ".kddttccccttddk.",
        ".kddttcCCcttddk.",
        ".kddttcCCcttddk.",
        ".kddttccccttddk.",
        ".kddttttttttddk.",
        ".kddddddddddddk.",
        ".kkkkkkkkkkkkkk.",
      ],
    ],
  },
  deepslate_pillar: {
    w: 12, h: 34, anchor: 'bottom',
    palette: { k: '#0a1416', d: '#1b2b30', t: '#2a3d42', c: '#2fd6d6', v: '#0f2228' },
    frames: [
      [
        "..kttttttk..",
        "..kddddddk..",
        "..kddddddk..",
        "..kddddddk..",
        "..kttttttk..",
        "..kddddddk..",
        "..kdvddddk..",
        "..kddddddk..",
        "..kttttttk..",
        "..kdcddddk..",
        "..kddddddk..",
        "..kddddvdk..",
        "..kttttttk..",
        "..kddddddk..",
        "..kddddddk..",
        "..kddddddk..",
        "..kttttttk..",
        "..kvdddddk..",
        "..kddddddk..",
        "..kddddddk..",
        "..kttttctk..",
        "..kddddddk..",
        "..kddddddk..",
        "..kdddddvk..",
        "..kttttttk..",
        "..kddddddk..",
        "..kddddddk..",
        "..kddcdddk..",
        "..kttttttk..",
        "..kddvdddk..",
        "..kddddddk..",
        "..kddddddk..",
        "..kttttttk..",
        "..kddddddk..",
      ],
    ],
  },
};
