// Shop sprites: character heads and pets, authored in parallel and validated.
export const SHOP = {
  head_knight: {
    w: 8, h: 8, anchor: 'center',
    palette: { p: '#c8302f', m: '#9aa1ad', h: '#c9cfd9', v: '#1d2027', s: '#e0a884', d: '#5a606c' },
    frames: [[
      "...pp...",
      "mmmppmmm",
      "hhhhhhhh",
      "mmmmmmmm",
      "mvssssvm",
      "mmmvvmmm",
      "mmmvvmmm",
      "dddddddd",
    ]],
  },
  head_wizard_c: {
    w: 8, h: 8, anchor: 'center',
    palette: { p: '#5b2a9a', d: '#3a1560', s: '#f0c9a4', w: '#ffffff', e: '#2a2a3a' },
    frames: [[
      ".pppppp.",
      "dddddddd",
      ".ssssss.",
      ".wwssww.",
      ".sesses.",
      ".wwwwww.",
      "wwwwwwww",
      "..wwww..",
    ]],
  },
  head_chef_c: {
    w: 8, h: 8, anchor: 'center',
    palette: { c: '#ffffff', b: '#e2e2e2', s: '#d8a077', e: '#2a1a10', m: '#3b2415' },
    frames: [[
      ".cccccc.",
      "cccccccc",
      "bbbbbbbb",
      "ssssssss",
      "sesssses",
      "ssssssss",
      "ssmmmmss",
      "ssssssss",
    ]],
  },
  head_ninja: {
    w: 8, h: 8, anchor: 'center',
    palette: { n: '#1e2a4a', d: '#101833', s: '#d8a077', e: '#ffffff', p: '#16203a' },
    frames: [[
      "ddnnnndd",
      "nnnnnnnd",
      "nnnnnnnd",
      "nnnnnnnd",
      "sepsspes",
      "nnnnnnnd",
      "nnnnnnnd",
      "ddnnnndd",
    ]],
  },
  head_pirate: {
    w: 8, h: 8, anchor: 'center',
    palette: { r: '#c0392b', d: '#8e2b22', s: '#d8a077', g: '#2a2a2a', b: '#101010', e: '#ffffff', k: '#1a1a1a', w: '#3a2418' },
    frames: [[
      "rrrrrrrr",
      "rdrrrrdr",
      "sggsssss",
      "gbbsssss",
      "sbbsseks",
      "ssssssss",
      "swwwwwws",
      "sswwwwss",
    ]],
  },
  head_pillager: {
    w: 8, h: 8, anchor: 'center',
    palette: { g: '#7a8f63', d: '#20241a', e: '#e6e6d2', b: '#1a1a14', n: '#6a7c54' },
    frames: [[
      "gggggggg",
      "gggggggg",
      "gddddddg",
      "gebnnbeg",
      "gggnnggg",
      "ggnnnngg",
      "ggddddgg",
      "gggggggg",
    ]],
  },
  head_witch_c: {
    w: 8, h: 8, anchor: 'center',
    palette: { k: '#1a1420', h: '#3b2038', g: '#7ac46a', n: '#5c9c4e', w: '#2b1a12', e: '#22142c', m: '#3a2030' },
    frames: [[
      "kkkkkkkk",
      "kkkkkkkk",
      "hhgggghh",
      "hhgggghh",
      "hgeggegh",
      "hggnnggh",
      "hggnwggh",
      "hggmmggh",
    ]],
  },
  head_slime: {
    w: 8, h: 8, anchor: 'center',
    palette: { g: '#5be36a', l: '#96f7a4', d: '#37a349', e: '#16341c' },
    frames: [[
      "dlllllld",
      "dlggggld",
      "dggggggd",
      "dggggggd",
      "dgeggegd",
      "dggggggd",
      "dggeeggd",
      "dddddddd",
    ]],
  },
  pet_cat: {
    w: 16, h: 12, anchor: 'bottom',
    palette: { k: '#2b1a12', o: '#e08a3c', l: '#f5c47a', d: '#a85f22', w: '#f7e3c4', g: '#4c9a4f' },
    frames: [[
      "..k...k.........",
      ".kok.kok........",
      ".kooooook.......",
      ".kogoodok....kk.",
      ".kwwooook...klk.",
      ".kwkoooooookkok.",
      ".kwodoodooookok.",
      ".kwoodoodoookok.",
      "..koooooooooook.",
      "..kokkkkkkkook..",
      "..kok......kok..",
      "..kwk......kwk..",
    ]],
  },
  pet_fox: {
    w: 16, h: 12, anchor: 'bottom',
    palette: { d: '#2b1a12', o: '#e0842f', w: '#f7f0e2', b: '#4a3020' },
    frames: [[
      "...........d..d.",
      "..........doddod",
      ".dd......doooood",
      "dwod.....dodoood",
      "dwoodddddooooowd",
      "dwooooooooooowd.",
      "dwoooooooowwwd..",
      "ddooooooowwwd...",
      ".ddbbddddbbd....",
      "...bd....bd.....",
      "...bd....bd.....",
      "..dbd...dbd.....",
    ]],
  },
  pet_bee: {
    w: 16, h: 13, anchor: 'bottom',
    palette: { o: '#241a08', y: '#ffcf2e', l: '#ffe89a', k: '#4a3312', w: '#f2fbff', W: '#bfe3f5', e: '#ffffff', g: '#d8dee6' },
    frames: [[
      ".............o.o",
      "....oooo....o.o.",
      "...owwwwo...oo..",
      "...owWWwo..oooo.",
      "..oooooooooyyyyo",
      "..olkklykkoyeoyo",
      "..oykkyykkolyyyo",
      ".goykkyykkoyyyo.",
      "ggoykkyykkoooo..",
      "..oykkyykko.....",
      "...oooooooo.....",
      "....o..o.o......",
      "...oo.oo.oo.....",
    ]],
  },
  pet_axolotl: {
    w: 16, h: 13, anchor: 'bottom',
    palette: { o: '#4a2a3a', p: '#f2a0bd', l: '#ffd2e2', g: '#ff7fae', w: '#ffffff', e: '#33202c' },
    frames: [[
      ".......o...o....",
      "......ogo.ogo...",
      ".....oggggggo...",
      "....oggggoooooo.",
      "....ogggoppweppo",
      "oooooooooppppppo",
      "opppppppppppppoo",
      "oppppllllllppo..",
      "oplllllllllppo..",
      "opooooooooooo...",
      "oo.op...op......",
      "...op...op......",
      "..ooo..ooo......",
    ]],
  },
  pet_chicken: {
    w: 16, h: 13, anchor: 'bottom',
    palette: { K: '#2b2118', W: '#ffffff', G: '#d8dce4', R: '#d94434', O: '#f5a623' },
    frames: [[
      "..........RR....",
      ".........KKKK...",
      "........KWWWK...",
      ".KK.....KWWKWOO.",
      ".KWK....KWWWKR..",
      ".KWWKKKKWWWWWK..",
      ".KWWWWWWWWWWWK..",
      ".KWWKGGGKWWWWK..",
      ".KWWKKKKKWWWK...",
      "..KKKKKKKKKKK...",
      ".....O...O......",
      ".....O...O......",
      "....OOO.OOO.....",
    ]],
  },
  pet_pig: {
    w: 16, h: 12, anchor: 'bottom',
    palette: { o: '#3a2028', p: '#f4a3bc', h: '#ffd0de', s: '#d1738f' },
    frames: [[
      "...oo...........",
      "..ohhoooooooo...",
      ".ohhhpphhppppoo.",
      "ohhhpppppppppo.o",
      "ohohpppppppppoo.",
      "ooshpppppppppo..",
      "osshpppppppppo..",
      "oosppppppppppo..",
      ".oppsssssssspo..",
      ".oppoppoppoppo..",
      ".oppoppoppoppo..",
      "..oo.oo.oo.oo...",
    ]],
  },
};
