// Pixel-art UI icons, authored in parallel and format-validated. These replace
// the emoji that used to stand in for buttons across the app shell.
export const UIICONS = {
  ui_back: {
    w: 12, h: 12, anchor: 'center',
    palette: { w: '#f5f7fb', g: '#a9b3c4', k: '#232a36' },
    frames: [[
      "............",
      ".....kk.....",
      "....kwk.....",
      "...kwwk.....",
      "..kwwwwkkkk.",
      ".kwwwwwwwwk.",
      ".kwwwwwwwwk.",
      "..kggggkkkk.",
      "...kggk.....",
      "....kgk.....",
      ".....kk.....",
      "............",
    ]],
  },
  ui_play: {
    w: 12, h: 12, anchor: 'center',
    palette: { g: '#5ce663', G: '#2b8a3e', k: '#12331a' },
    frames: [[
      ".k..........",
      ".kk.........",
      ".kgkk.......",
      ".kgggkk.....",
      ".kgggggkk...",
      ".kgggggggkk.",
      ".kggggggGkk.",
      ".kgggGGkk...",
      ".kggGkk.....",
      ".kGkk.......",
      ".kk.........",
      ".k..........",
    ]],
  },
  ui_world: {
    w: 12, h: 12, anchor: 'center',
    palette: { k: '#14293f', b: '#4fb0e8', B: '#2a76ac', g: '#68c65a', G: '#37913f' },
    frames: [[
      "....kkkk....",
      "..kkbbbbkk..",
      ".kbgggbbbbk.",
      ".kBggGBBBBk.",
      "kbggGbbgggbk",
      "kbbGbbbggGbk",
      "kbbbbbbgGbbk",
      "kbbggbbgbbbk",
      ".kBgGBBBBBk.",
      ".kbbgGbbbbk.",
      "..kkbbbbkk..",
      "....kkkk....",
    ]],
  },
  ui_pickaxe: {
    w: 13, h: 13, anchor: 'center',
    palette: { k: '#2b2118', g: '#d4dae2', G: '#8a94a3', w: '#b07a3c', W: '#6e4a24' },
    frames: [[
      ".kk.......kk.",
      "kggkkkkkkkGGk",
      "kgggggggggggk",
      "kggggggggGGGk",
      ".kGGGGGGGGGk.",
      "..kkkkwWkkk..",
      ".....kwWk....",
      "......kwWk...",
      "......kwWk...",
      ".......kwWk..",
      ".......kwWk..",
      "........kwWk.",
      "........kkkk.",
    ]],
  },
  ui_person: {
    w: 12, h: 12, anchor: 'center',
    palette: { k: '#2b1d12', s: '#e0a878', S: '#b5794e', t: '#2fa8a8', T: '#1c7175' },
    frames: [[
      "...kkkkkk...",
      "..kssssssk..",
      "..kskssksk..",
      "..ksssssSk..",
      "...ksssSk...",
      "...kksskk...",
      "..kkksskkk..",
      ".ktttTTtttk.",
      "kttttttttttk",
      "kttttttttTTk",
      "kttttttttTTk",
      "kkkkkkkkkkkk",
    ]],
  },
  ui_trophy: {
    w: 13, h: 13, anchor: 'center',
    palette: { g: '#ffd94d', G: '#c9a02c', k: '#3a2408', b: '#7a4a1e' },
    frames: [[
      ".kkkkkkkkkkk.",
      "kkgggggggggkk",
      "kgkgggggggkgk",
      "kgkGgggggGkgk",
      "kkkGgggggGkkk",
      "..kGgggggGk..",
      "..kkGgggGkk..",
      "....kGGGk....",
      "....kgggk....",
      "...kkgggkk...",
      "..kkkkkkkkk..",
      "..kbbbbbbbk..",
      "..kkkkkkkkk..",
    ]],
  },
  ui_gear: {
    w: 13, h: 13, anchor: 'center',
    palette: { k: '#2f2f38', g: '#b0b4bd', G: '#767b86', h: '#e4e7ee' },
    frames: [[
      "....kkkkk....",
      "....khggk....",
      "...khhgggk...",
      "..khhgggggk..",
      "kkkhGGGGGgkkk",
      "khggG...Ggggk",
      "kgggG...Ggggk",
      "kgggG...GgGGk",
      "kkkgGGGGGgkkk",
      "..kggggGGGk..",
      "...kgGGGGk...",
      "....kGGGk....",
      "....kkkkk....",
    ]],
  },
  ui_info: {
    w: 12, h: 12, anchor: 'center',
    palette: { b: '#4aa8f0', B: '#2a6fc0', k: '#10294f', w: '#ffffff' },
    frames: [[
      "....kkkk....",
      "..kkbbbbkk..",
      ".kbbbwwbbBk.",
      ".kbbbwwbbBk.",
      "kbbbbbbbbBBk",
      "kbbbbwwbbbBk",
      "kbbbbwwbbbBk",
      "kbbbbwwbbbBk",
      "kbbbbwwbbBBk",
      ".kbbbwwbBBk.",
      "..kkbbBBkk..",
      "....kkkk....",
    ]],
  },
  ui_house: {
    w: 13, h: 13, anchor: 'center',
    palette: { k: '#2e1c10', r: '#d94b3f', R: '#a02f27', w: '#c9954f', W: '#96662f' },
    frames: [[
      "......k......",
      ".....krk.....",
      "....krrrk....",
      "...krrrrrk...",
      "..krrrrrRRk..",
      ".krrrrrrRRRk.",
      "kkkkkkkkkkkkk",
      ".kwwwwwwwwWk.",
      ".kwwwwwwwwWk.",
      ".kwwwkkkwwWk.",
      ".kwwwkkkwwWk.",
      ".kwwwkkkwwWk.",
      ".kkkkkkkkkkk.",
    ]],
  },
  ui_bow: {
    w: 12, h: 12, anchor: 'center',
    palette: { k: '#2b1a0e', b: '#a9743f', B: '#6b431f', s: '#f2ead6' },
    frames: [[
      "...k........",
      "...sbk......",
      "..s..bk.....",
      ".s....bk....",
      ".s....bk.kk.",
      "sBBBBBBBBkkk",
      "s.....bk.kk.",
      ".s....bk....",
      ".s....bk....",
      "..s..bk.....",
      "...sbk......",
      "...k........",
    ]],
  },
  ui_door: {
    w: 11, h: 13, anchor: 'center',
    palette: { k: '#2b1a0c', w: '#a97c4a', W: '#6f4a26', g: '#ffd94d', G: '#c08a1e' },
    frames: [[
      "kkkkkkkkkkk",
      "kWWWWWWWWWk",
      "kwwWwwWwwWk",
      "kwwWwwWwwWk",
      "kwwWwwWwwWk",
      "kwwWwwWwwWk",
      "kwwWwwWggWk",
      "kwwWwwWGGWk",
      "kwwWwwWwwWk",
      "kwwWwwWwwWk",
      "kwwWwwWwwWk",
      "kWWWWWWWWWk",
      "kkkkkkkkkkk",
    ]],
  },
  ui_sound_on: {
    w: 13, h: 11, anchor: 'center',
    palette: { w: '#f4f4f4', g: '#a0a8b4', k: '#241f2e' },
    frames: [[
      ".....k.......",
      "....kk....k..",
      "...kwk....wk.",
      "kkkwwk.k...wk",
      "kwwwwk.wk..wk",
      "kwwwwk.wk..wk",
      "kggggk.wk..wk",
      "kkkggk.k...wk",
      "...kgk....wk.",
      "....kk....k..",
      ".....k.......",
    ]],
  },
  ui_sound_off: {
    w: 14, h: 13, anchor: 'center',
    palette: { k: '#2b2018', s: '#d7dde6', d: '#94a1b0', r: '#e8483c', R: '#9c2b22' },
    frames: [[
      "..............",
      ".....k........",
      "....kk........",
      "...ksk.rr...rr",
      "kkkssk.rrr.rrr",
      "kssssk..rrrrr.",
      "kssssk...rrr..",
      "ksdddk..RrrrR.",
      "kkkddk.RRr.rRR",
      "...kdk.RR...RR",
      "....kk........",
      ".....k........",
      "..............",
    ]],
  },
  ui_camera: {
    w: 12, h: 12, anchor: 'center',
    palette: { k: '#1c1c22', d: '#3d424e', g: '#6b7280', b: '#3d9be9', w: '#bfe4ff' },
    frames: [[
      "..kkkk......",
      "..kddk......",
      "kkkkkkkkkkkk",
      "kggggggggddk",
      "kgggkkkkgddk",
      "kggkbbbbkddk",
      "kggkwbbbkddk",
      "kggkbbbbkddk",
      "kggkbbbbkddk",
      "kgggkkkkgddk",
      "kggddddddddk",
      "kkkkkkkkkkkk",
    ]],
  },
  ui_trash: {
    w: 12, h: 13, anchor: 'center',
    palette: { k: '#33383f', g: '#a8b0b8', G: '#6e767f', w: '#c9d1d9' },
    frames: [[
      ".....kk.....",
      "....kggk....",
      ".kkkkkkkkkk.",
      ".kwwwwwwwwk.",
      ".kkkkkkkkkk.",
      "..kgGggGgk..",
      "..kgGggGgk..",
      "..kgGggGgk..",
      "..kgGggGgk..",
      "...kGggGk...",
      "...kGggGk...",
      "...kGggGk...",
      "...kkkkkk...",
    ]],
  },
  ui_bag: {
    w: 12, h: 12, anchor: 'center',
    palette: { k: '#3a2413', b: '#a9743f', B: '#7a4f28', t: '#f2c14e' },
    frames: [[
      "....kkkk....",
      "....k..k....",
      "kkkkkkkkkkkk",
      "kbbbbbbbbbbk",
      "kbbbbbbbbbbk",
      "kkkkkttkkkkk",
      "kbbbbbbbbbbk",
      "kbbbbbbbbbBk",
      "kbbbbbbbbbBk",
      "kbbbbbbbbBBk",
      "kBBBBBBBBBBk",
      "kkkkkkkkkkkk",
    ]],
  },
  ui_sofa: {
    w: 13, h: 12, anchor: 'center',
    palette: { k: '#3a1b14', h: '#d97a58', r: '#b4472f', R: '#7d2c1e', w: '#4a2b1c' },
    frames: [[
      ".kkkkkkkkkkk.",
      ".khhhhhhhhhk.",
      ".krrrrrrrrrk.",
      ".krrrrrrrrrk.",
      ".kRRRRRRRRRk.",
      "kkkkRRRRRkkkk",
      "khhkhhhhhkhhk",
      "krrkrrrrrkrrk",
      "kRRkrrrrrkRRk",
      "kRRRRRRRRRRRk",
      "kkkkkkkkkkkkk",
      ".ww.......ww.",
    ]],
  },
  ui_palette: {
    w: 12, h: 12, anchor: 'center',
    palette: { k: '#3a2416', t: '#d9a86c', r: '#e0452f', g: '#4cc24c', b: '#3f7fe0' },
    frames: [[
      "...kkkkkk...",
      ".kkttttttkk.",
      "kttttttttttk",
      "ktrrtggtbbtk",
      "ktrrtggtbbtk",
      "kttttttttttk",
      "ktttkkkkkttk",
      "ktttk...kttk",
      "ktttk...kttk",
      "ktttkkkkkttk",
      ".kkttttttkk.",
      "...kkkkkk...",
    ]],
  },
  ui_lock: {
    w: 12, h: 12, anchor: 'center',
    palette: { k: '#2a1e12', s: '#c8d0da', S: '#8792a3', g: '#f2c033', G: '#a97416' },
    frames: [[
      "..kkkkkkkk..",
      ".kssssssSSk.",
      ".kssk..kSSk.",
      ".kssk..kSSk.",
      ".kssk..kSSk.",
      "kkkkkkkkkkkk",
      "kgggggggggGk",
      "kgggkkkkggGk",
      "kgggkkkkgGGk",
      "kggggkkggGGk",
      "kgggggggGGGk",
      "kkkkkkkkkkkk",
    ]],
  },
  ui_pause: {
    w: 13, h: 12, anchor: 'center',
    palette: { w: '#ffffff', s: '#c3cfdd', k: '#2a3446' },
    frames: [[
      ".............",
      ".kkkkk.kkkkk.",
      ".kwwwk.kwwwk.",
      ".kwwwk.kwwwk.",
      ".kwwsk.kwwsk.",
      ".kwwsk.kwwsk.",
      ".kwwsk.kwwsk.",
      ".kwwsk.kwwsk.",
      ".kwwsk.kwwsk.",
      ".kwwsk.kwwsk.",
      ".kkkkk.kkkkk.",
      ".............",
    ]],
  },
};
