// Build static/rescue.html: bundle js/rescue-entry.js and inline it into the
// template as a single <script>.
//
// The rescue page is what a player reaches when the app's own modules have
// already failed them, so the built page must have NO RUNTIME MODULE GRAPH — no
// imports, no chunks, no evaluation order to get wrong. That is the property
// that matters, and it is not the same as "no npm packages": a library bundled
// INTO the file is just part of the file, exactly like Svelte is for the app.
//
// Usage: node tools/build-rescue.mjs
import { build } from 'vite';
import { readFileSync, writeFileSync } from 'node:fs';

const TEMPLATE = 'src/rescue.template.html';
const ENTRY = 'js/rescue-entry.js';
const OUT = 'static/rescue.html';
const MARKER = '/*__RESCUE_BUNDLE__*/';

const result = await build({
  configFile: false,
  logLevel: 'silent',
  build: {
    write: false,
    // iife, so the output is a self-contained script tag with nothing to import
    lib: { entry: ENTRY, formats: ['iife'], name: 'CraftRushRescue' },
  },
});

const chunk = result[0].output.find((o) => o.type === 'chunk');
if (!chunk) throw new Error('the rescue bundle produced no code');

const template = readFileSync(TEMPLATE, 'utf8');
if (!template.includes(MARKER)) throw new Error(`${TEMPLATE} has no ${MARKER} placeholder`);

// Inside a <script> element the HTML parser is not looking at JavaScript, it is
// looking for byte sequences. `</script` closes the tag, and `<!--` flips it into
// the escaped state where a later `<script` changes when it closes. The bundled
// library legitimately contains all three inside strings and regexes, which broke
// the page with "Unexpected token '<'". \x3C is the same character to JS and
// invisible to the HTML parser.
const safe = chunk.code
  .replace(/<\/script/gi, '\\x3C/script')
  .replace(/<!--/g, '\\x3C!--')
  .replace(/<script/gi, '\\x3Cscript');

// A FUNCTION replacement, not a string: minified code is full of `$`, and
// String.replace treats $& and friends as substitution patterns, which silently
// mangles the bundle. This corrupted the page into a syntax error once already.
const html = template
  .replace(MARKER, () => safe)
  .replace('<!DOCTYPE html>', '<!DOCTYPE html>\n<!-- GENERATED by tools/build-rescue.mjs from src/rescue.template.html — do not edit. -->');

writeFileSync(OUT, html);

const kb = (Buffer.byteLength(html) / 1024).toFixed(0);
console.log(`built ${OUT} — one self-contained file, ${kb}KB, no runtime imports`);
