// Bundle every theme's data into one plain JS module.
//
// This exists to kill a top-level await. theme.js used to FETCH its data, which
// made it an async module, which under code splitting changes the order chunks
// evaluate in. Safari enforces that order differently from Chromium: the page
// chunk ran before the chunk holding Svelte's helpers had initialised, and the
// game died on `ki is not a function` with no useful stack, while every browser
// I could test in was fine.
//
// A theme's data is about 24KB. Inlining it costs less than the ten requests it
// replaces, removes the async module entirely, and means the game cannot fail to
// start because a JSON file was slow, blocked or cached wrong.
//
// The atlas PNG is still fetched, but that happens inside initAssets where a
// failure is caught and degrades to placeholder art rather than killing the app.
//
// Usage: node tools/pack-themes.mjs
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const SRC = 'themes';
const OUT = 'js/themes.generated.js';

const ids = readdirSync(SRC, { withFileTypes: true })
  .filter((d) => d.isDirectory() && existsSync(join(SRC, d.name, 'theme.json')))
  .map((d) => d.name)
  .sort();

if (!ids.length) throw new Error('no themes found under themes/');

const themes = {};
for (const id of ids) {
  const manifest = JSON.parse(readFileSync(join(SRC, id, 'theme.json'), 'utf8'));
  const data = {};
  for (const part of manifest.data || []) {
    data[part] = JSON.parse(readFileSync(join(SRC, id, `${part}.json`), 'utf8'));
  }
  themes[id] = { manifest, data };
}

const body = `// GENERATED by tools/pack-themes.mjs — do not edit.
//
// Every theme's data, inlined. The source of truth is themes/<id>/*.json; run
// \`npm run art\` after changing one. This is generated rather than fetched so
// that loading a theme cannot be async: a top-level await here changes chunk
// evaluation order under bundling and broke the game in Safari. See #69.

/** @type {Record<string, {manifest: any, data: any}>} */
export const THEMES = ${JSON.stringify(themes, null, 1)};

export const THEME_IDS = ${JSON.stringify(ids)};
`;

writeFileSync(OUT, body);
const kb = (Buffer.byteLength(body) / 1024).toFixed(0);
console.log(`packed ${ids.length} theme${ids.length === 1 ? '' : 's'} (${ids.join(', ')}) into ${OUT}, ${kb}KB`);
